export const options1 = [
	{ key: "Vente", value: "Vente" },
	{ key: "Echange", value: "Echange" },
	{ key: "Location", value: "Location" },
	{ key: "Loc pour vacances", value: "Loc pour vacances" },
];
export const options2 = [
	{ key: " Terrain", value: " Terrain" },
	{ key: "Terrain Agricole", value: "Terrain Agricole" },
	{ key: "Appartement", value: "Appartement" },
	{ key: "Maison", value: "Maison" },
	{ key: "Bungalow", value: "Bungalow" },
];

export const options3 = [
	{ key: "Adrar", value: "Adrar" },
	{ key: "Chlef", value: "Chlef" },
	{ key: "Laghouat", value: "Laghouat" },
	{ key: "Oum El Bouaghi", value: "Oum El Bouaghi" },
	{ key: "Batna", value: "Batna" },
	{ key: "Béjaïa", value: "Béjaïa" },
	{ key: "Biskra", value: "Biskra" },
	{ key: "Béchar", value: "Béchar" },
	{ key: "Blida", value: "Blida" },
	{ key: "Bouira", value: "Bouira" },
	{ key: "Tamanrasset", value: "Tamanrasset" },
	{ key: "Tébessa", value: "Tébessa" },
	{ key: "Tlemcen", value: "Tlemcen" },
	{ key: "Tiaret", value: "Tiaret" },
	{ key: "Tizi Ouzou", value: "Tizi Ouzou" },
	{ key: "Alger", value: "Alger" },
	{ key: "Djelfa", value: "Djelfa" },
	{ key: "Jijel", value: "Jijel" },
	{ key: "Sétif", value: "Sétif" },
	{ key: "Saïda", value: "Saïda" },
	{ key: "Skikda", value: "Skikda" },
	{ key: "Sidi Bel Abbès", value: "Sidi Bel Abbès" },
	{ key: "Annaba", value: "Annaba" },
	{ key: "Guelma", value: "Guelma" },
	{ key: "Constantine", value: "Constantine" },
	{ key: "Médéa", value: "Médéa" },
	{ key: "Mostaganem", value: "Mostaganem" },
	{ key: "M'Sila", value: "M'Sila" },
	{ key: "Mascara", value: "Mascara" },
	{ key: "Ouargla", value: "Ouargla" },
	{ key: "Oran", value: "Oran" },
	{ key: "El Bayadh", value: "El Bayadh" },
	{ key: "Illizi", value: "Illizi" },
	{ key: "Bordj Bou Arreridj", value: "Bordj Bou Arreridj" },
	{ key: "Boumerdès", value: "Boumerdès" },
	{ key: "El Tarf", value: "El Tarf" },
	{ key: "Tindouf", value: "Tindouf" },
	{ key: "Tissemsilt", value: "Tissemsilt" },
	{ key: "El Oued", value: "El Oued" },
	{ key: "Khenchela", value: "Khenchela" },
	{ key: "Souk Ahras", value: "Souk Ahras" },
	{ key: "Tipaza", value: "Tipaza" },
	{ key: "Mila", value: "Mila" },
	{ key: "Aïn Defla", value: "Aïn Defla" },
	{ key: "Naâma", value: "Naâma" },
	{ key: "Aïn Témouchent", value: "Aïn Témouchent" },
	{ key: "Ghardaïa", value: "Ghardaïa" },
	{ key: "Relizane", value: "Relizane" },
	{ key: "Timimoun", value: "Timimoun" },
	{ key: "Bordj Badji Mokhtar", value: "Bordj Badji Mokhtar" },
	{ key: "Ouled Djellal", value: "Ouled Djellal" },
	{ key: "Béni Abbès", value: "Béni Abbès" },
	{ key: "In Salah", value: "In Salah" },
	{ key: "In Guezzam", value: "In Guezzam" },
	{ key: "Touggourt", value: "Touggourt" },
	{ key: "Djanet", value: "Djanet" },
	{ key: "El Meghaier", value: "El Meghaier" },
	{ key: "El Menia", value: "El Menia" },
];

export const comm = {
	Adrar: [
		{ key: "Timekten", value: "Timekten" },
		{ key: "Bouda", value: "Bouda" },
		{ key: "Ouled Ahmed Timmi", value: "Ouled Ahmed Timmi" },
		{ key: "Adrar", value: "Adrar" },
		{ key: "Fenoughil", value: "Fenoughil" },
		{ key: "In Zghmir", value: "In Zghmir" },
		{ key: "Reggane", value: "Reggane" },
		{ key: "Sali", value: "Sali" },
		{ key: "Sebaa", value: "Sebaa" },
		{ key: "Tsabit", value: "Tsabit" },
		{ key: "Tamest", value: "Tamest" },
		{ key: "Tamantit", value: "Tamantit" },
		{ key: "Tit", value: "Tit" },
		{ key: "Zaouiet Kounta", value: "Zaouiet Kounta" },
		{ key: "Akabli", value: "Akabli" },
		{ key: "Aoulef", value: "Aoulef" },
	],
	Chlef: [
		{ key: "Talassa", value: "Talassa" },
		{ key: "Zeboudja", value: "Zeboudja" },
		{ key: "El Hadjadj", value: "El Hadjadj" },
		{ key: "Ouled Ben Abdelkader", value: "Ouled Ben Abdelkader" },
		{ key: "Ain Merane", value: "Ain Merane" },
		{ key: "Breira", value: "Breira" },
		{ key: "Ouled Abbes", value: "Ouled Abbes" },
		{ key: "Oued Fodda", value: "Oued Fodda" },
		{ key: "Beni Rached", value: "Beni Rached" },
		{ key: "Herenfa", value: "Herenfa" },
		{ key: "Tadjena", value: "Tadjena" },
		{ key: "El Marsa", value: "El Marsa" },
		{ key: "Chlef", value: "Chlef" },
		{ key: "Oum Drou", value: "Oum Drou" },
		{ key: "Sendjas", value: "Sendjas" },
		{ key: "Sidi Abderrahmane", value: "Sidi Abderrahmane" },
		{ key: "Sidi Akkacha", value: "Sidi Akkacha" },
		{ key: "Tenes", value: "Tenes" },
		{ key: "Beni  Bouattab", value: "Beni  Bouattab" },
		{ key: "El Karimia", value: "El Karimia" },
		{ key: "Harchoun", value: "Harchoun" },
		{ key: "Bouzeghaia", value: "Bouzeghaia" },
		{ key: "Taougrit", value: "Taougrit" },
		{ key: "Beni Haoua", value: "Beni Haoua" },
		{ key: "Abou El Hassane", value: "Abou El Hassane" },
		{ key: "Oued Goussine", value: "Oued Goussine" },
		{ key: "Chettia", value: "Chettia" },
		{ key: "Moussadek", value: "Moussadek" },
		{ key: "Ouled Fares", value: "Ouled Fares" },
		{ key: "Boukadir", value: "Boukadir" },
		{ key: "Oued Sly", value: "Oued Sly" },
		{ key: "Sobha", value: "Sobha" },
		{ key: "Benairia", value: "Benairia" },
		{ key: "Labiod Medjadja", value: "Labiod Medjadja" },
		{ key: "Dahra", value: "Dahra" },
	],
	Laghouat: [
		{ key: "El Beidha", value: "El Beidha" },
		{ key: "Gueltat Sidi Saad", value: "Gueltat Sidi Saad" },
		{ key: "Brida", value: "Brida" },
		{ key: "Ain Sidi Ali", value: "Ain Sidi Ali" },
		{ key: "Tadjemout", value: "Tadjemout" },
		{ key: "Hadj Mechri", value: "Hadj Mechri" },
		{ key: "Taouiala", value: "Taouiala" },
		{ key: "El Ghicha", value: "El Ghicha" },
		{ key: "Tadjrouna", value: "Tadjrouna" },
		{ key: "Sebgag", value: "Sebgag" },
		{ key: "Sidi Bouzid", value: "Sidi Bouzid" },
		{ key: "Oued Morra", value: "Oued Morra" },
		{ key: "Laghouat", value: "Laghouat" },
		{ key: "Oued M'zi", value: "Oued M'zi" },
		{ key: "Ksar El Hirane", value: "Ksar El Hirane" },
		{ key: "El Assafia", value: "El Assafia" },
		{ key: "Sidi Makhlouf", value: "Sidi Makhlouf" },
		{ key: "Hassi Delaa", value: "Hassi Delaa" },
		{ key: "Hassi R'mel", value: "Hassi R'mel" },
		{ key: "Ain Madhi", value: "Ain Madhi" },
		{ key: "El Haouaita", value: "El Haouaita" },
		{ key: "Kheneg", value: "Kheneg" },
		{ key: "Benacer Benchohra", value: "Benacer Benchohra" },
		{ key: "Aflou", value: "Aflou" },
	],
	"Oum El Bouaghi": [
		{ key: "Fkirina", value: "Fkirina" },
		{
			key: "El Fedjoudj Boughrara Sa",
			value: "El Fedjoudj Boughrara Sa",
		},
		{ key: "Ain Fekroun", value: "Ain Fekroun" },
		{ key: "Rahia", value: "Rahia" },
		{ key: "Meskiana", value: "Meskiana" },
		{ key: "El Belala", value: "El Belala" },
		{ key: "Behir Chergui", value: "Behir Chergui" },
		{ key: "Ksar Sbahi", value: "Ksar Sbahi" },
		{ key: "Souk Naamane", value: "Souk Naamane" },
		{ key: "Ouled Zouai", value: "Ouled Zouai" },
		{ key: "Oum El Bouaghi", value: "Oum El Bouaghi" },
		{ key: "Ain Babouche", value: "Ain Babouche" },
		{ key: "Ain Zitoun", value: "Ain Zitoun" },
		{ key: "Bir Chouhada", value: "Bir Chouhada" },
		{ key: "Ain Beida", value: "Ain Beida" },
		{ key: "Berriche", value: "Berriche" },
		{ key: "Zorg", value: "Zorg" },
		{ key: "Ain M'lila", value: "Ain M'lila" },
		{ key: "Ouled Gacem", value: "Ouled Gacem" },
		{ key: "Ouled Hamla", value: "Ouled Hamla" },
		{ key: "El Amiria", value: "El Amiria" },
		{ key: "Sigus", value: "Sigus" },
		{ key: "Oued Nini", value: "Oued Nini" },
		{ key: "Ain Diss", value: "Ain Diss" },
		{ key: "Dhalaa", value: "Dhalaa" },
		{ key: "El Djazia", value: "El Djazia" },
		{ key: "Ain Kercha", value: "Ain Kercha" },
		{ key: "El Harmilia", value: "El Harmilia" },
		{ key: "Hanchir Toumghani", value: "Hanchir Toumghani" },
	],
	Batna: [
		{ key: "Maafa", value: "Maafa" },
		{ key: "Gosbat", value: "Gosbat" },
		{ key: "Timgad", value: "Timgad" },
		{ key: "Taxlent", value: "Taxlent" },
		{ key: "Ouled Si Slimane", value: "Ouled Si Slimane" },
		{ key: "Lemcene", value: "Lemcene" },
		{ key: "Talkhamt", value: "Talkhamt" },
		{ key: "Ras El Aioun", value: "Ras El Aioun" },
		{ key: "Rahbat", value: "Rahbat" },
		{ key: "Ouled Sellem", value: "Ouled Sellem" },
		{ key: "Guigba", value: "Guigba" },
		{ key: "Teniet El Abed", value: "Teniet El Abed" },
		{ key: "Batna", value: "Batna" },
		{ key: "Fesdis", value: "Fesdis" },
		{ key: "Oued Chaaba", value: "Oued Chaaba" },
		{ key: "Hidoussa", value: "Hidoussa" },
		{ key: "Ksar Bellezma", value: "Ksar Bellezma" },
		{ key: "Merouana", value: "Merouana" },
		{ key: "Oued El Ma", value: "Oued El Ma" },
		{ key: "Lazrou", value: "Lazrou" },
		{ key: "Seriana", value: "Seriana" },
		{ key: "Zanet El Beida", value: "Zanet El Beida" },
		{ key: "Menaa", value: "Menaa" },
		{ key: "Tigharghar", value: "Tigharghar" },
		{ key: "Ain Yagout", value: "Ain Yagout" },
		{ key: "Boumia", value: "Boumia" },
		{ key: "Djerma", value: "Djerma" },
		{ key: "El Madher", value: "El Madher" },
		{ key: "Ouyoun El Assafir", value: "Ouyoun El Assafir" },
		{ key: "Tazoult", value: "Tazoult" },
		{ key: "Boumagueur", value: "Boumagueur" },
		{ key: "N Gaous", value: "N Gaous" },
		{ key: "Sefiane", value: "Sefiane" },
		{ key: "Arris", value: "Arris" },
		{ key: "Tighanimine", value: "Tighanimine" },
		{ key: "Ain Djasser", value: "Ain Djasser" },
		{ key: "El Hassi", value: "El Hassi" },
		{ key: "Seggana", value: "Seggana" },
		{ key: "Tilatou", value: "Tilatou" },
		{ key: "Foum Toub", value: "Foum Toub" },
		{ key: "Ichemoul", value: "Ichemoul" },
		{ key: "Inoughissen", value: "Inoughissen" },
		{ key: "Bouzina", value: "Bouzina" },
		{ key: "Larbaa", value: "Larbaa" },
		{ key: "Boulhilat", value: "Boulhilat" },
		{ key: "Chemora", value: "Chemora" },
		{ key: "Barika", value: "Barika" },
		{ key: "Bitam", value: "Bitam" },
		{ key: "M Doukal", value: "M Doukal" },
		{ key: "Azil Abedelkader", value: "Azil Abedelkader" },
		{ key: "Djezzar", value: "Djezzar" },
		{ key: "Ouled Ammar", value: "Ouled Ammar" },
		{ key: "Ghassira", value: "Ghassira" },
		{ key: "Kimmel", value: "Kimmel" },
		{ key: "T Kout", value: "T Kout" },
		{ key: "Ain Touta", value: "Ain Touta" },
		{
			key: "Beni Foudhala El Hakania",
			value: "Beni Foudhala El Hakania",
		},
		{ key: "Ouled Fadel", value: "Ouled Fadel" },
		{ key: "Ouled Aouf", value: "Ouled Aouf" },
		{ key: "Chir", value: "Chir" },
		{ key: "Oued Taga", value: "Oued Taga" },
	],
	Béjaïa: [
		{ key: "Sidi Ayad", value: "Sidi Ayad" },
		{ key: "Barbacha", value: "Barbacha" },
		{ key: "Leflaye", value: "Leflaye" },
		{ key: "Kendira", value: "Kendira" },
		{ key: "Sidi-Aich", value: "Sidi-Aich" },
		{ key: "Tifra", value: "Tifra" },
		{ key: "Tinebdar", value: "Tinebdar" },
		{ key: "El Kseur", value: "El Kseur" },
		{ key: "Fenaia Il Maten", value: "Fenaia Il Maten" },
		{ key: "Toudja", value: "Toudja" },
		{ key: "Dra El Caid", value: "Dra El Caid" },
		{ key: "Kherrata", value: "Kherrata" },
		{ key: "Bejaia", value: "Bejaia" },
		{ key: "Oued Ghir", value: "Oued Ghir" },
		{ key: "Benimaouche", value: "Benimaouche" },
		{ key: "Beni Djellil", value: "Beni Djellil" },
		{ key: "Feraoun", value: "Feraoun" },
		{ key: "Smaoun", value: "Smaoun" },
		{ key: "Timezrit", value: "Timezrit" },
		{ key: "Melbou", value: "Melbou" },
		{ key: "Souk El Tenine", value: "Souk El Tenine" },
		{ key: "Tamridjet", value: "Tamridjet" },
		{ key: "Boukhelifa", value: "Boukhelifa" },
		{ key: "Tala Hamza", value: "Tala Hamza" },
		{ key: "Tichy", value: "Tichy" },
		{ key: "Ait R'zine", value: "Ait R'zine" },
		{ key: "Ighil-Ali", value: "Ighil-Ali" },
		{ key: "Ait-Smail", value: "Ait-Smail" },
		{ key: "Darguina", value: "Darguina" },
		{ key: "Taskriout", value: "Taskriout" },
		{ key: "Aokas", value: "Aokas" },
		{ key: "Tizi-N'berber", value: "Tizi-N'berber" },
		{ key: "Adekar", value: "Adekar" },
		{ key: "Beni K'sila", value: "Beni K'sila" },
		{ key: "Taourit Ighil", value: "Taourit Ighil" },
		{ key: "Akbou", value: "Akbou" },
		{ key: "Chellata", value: "Chellata" },
		{ key: "Ighram", value: "Ighram" },
		{ key: "Tamokra", value: "Tamokra" },
		{ key: "Amalou", value: "Amalou" },
		{ key: "Bouhamza", value: "Bouhamza" },
		{ key: "M'cisna", value: "M'cisna" },
		{ key: "Seddouk", value: "Seddouk" },
		{ key: "Beni-Mallikeche", value: "Beni-Mallikeche" },
		{ key: "Boudjellil", value: "Boudjellil" },
		{ key: "Tazmalt", value: "Tazmalt" },
		{ key: "Akfadou", value: "Akfadou" },
		{ key: "Chemini", value: "Chemini" },
		{ key: "Souk Oufella", value: "Souk Oufella" },
		{ key: "Tibane", value: "Tibane" },
		{ key: "Ouzellaguen", value: "Ouzellaguen" },
		{ key: "Amizour", value: "Amizour" },
	],
	Biskra: [
		{ key: "El Feidh", value: "El Feidh" },
		{ key: "Lichana", value: "Lichana" },
		{ key: "Bouchakroun", value: "Bouchakroun" },
		{ key: "Mekhadma", value: "Mekhadma" },
		{ key: "Djemorah", value: "Djemorah" },
		{ key: "Branis", value: "Branis" },
		{ key: "El Outaya", value: "El Outaya" },
		{ key: "El Kantara", value: "El Kantara" },
		{ key: "Khenguet Sidi Nadji", value: "Khenguet Sidi Nadji" },
		{ key: "Ain Zaatout", value: "Ain Zaatout" },
		{ key: "Zeribet El Oued", value: "Zeribet El Oued" },
		{ key: "Meziraa", value: "Meziraa" },
		{ key: "Biskra", value: "Biskra" },
		{ key: "El Hadjab", value: "El Hadjab" },
		{ key: "M'lili", value: "M'lili" },
		{ key: "Foughala", value: "Foughala" },
		{ key: "El Ghrous", value: "El Ghrous" },
		{ key: "Bordj Ben Azzouz", value: "Bordj Ben Azzouz" },
		{ key: "Ourlal", value: "Ourlal" },
		{ key: "Oumache", value: "Oumache" },
		{ key: "Ain Naga", value: "Ain Naga" },
		{ key: "Chetma", value: "Chetma" },
		{ key: "El Haouch", value: "El Haouch" },
		{ key: "Sidi Okba", value: "Sidi Okba" },
		{ key: "M'chouneche", value: "M'chouneche" },
		{ key: "Lioua", value: "Lioua" },
		{ key: "Tolga", value: "Tolga" },
	],
	Béchar: [
		{ key: "Bechar", value: "Bechar" },
		{ key: "Boukais", value: "Boukais" },
		{ key: "Lahmar", value: "Lahmar" },
		{ key: "Mogheul", value: "Mogheul" },
		{ key: "Meridja", value: "Meridja" },
		{ key: "Taghit", value: "Taghit" },
		{ key: "Abadla", value: "Abadla" },
		{ key: "Erg-Ferradj", value: "Erg-Ferradj" },
		{
			key: "Machraa-Houari-Boumediene",
			value: "Machraa-Houari-Boumediene",
		},
		{ key: "Beni-Ounif", value: "Beni-Ounif" },
		{ key: "Tabelbala", value: "Tabelbala" },
		{ key: "Kenadsa", value: "Kenadsa" },
	],
	Blida: [
		{ key: "Beni Mered", value: "Beni Mered" },
		{ key: "Ouled Slama", value: "Ouled Slama" },
		{ key: "Mouzaia", value: "Mouzaia" },
		{ key: "Hammam Elouane", value: "Hammam Elouane" },
		{ key: "Bougara", value: "Bougara" },
		{ key: "Souhane", value: "Souhane" },
		{ key: "Larbaa", value: "Larbaa" },
		{ key: "Soumaa", value: "Soumaa" },
		{ key: "Guerrouaou", value: "Guerrouaou" },
		{ key: "Boufarik", value: "Boufarik" },
		{ key: "Meftah", value: "Meftah" },
		{ key: "Chiffa", value: "Chiffa" },
		{ key: "Ain Romana", value: "Ain Romana" },
		{ key: "Oued  Djer", value: "Oued  Djer" },
		{ key: "El-Affroun", value: "El-Affroun" },
		{ key: "Ouled Yaich", value: "Ouled Yaich" },
		{ key: "Chrea", value: "Chrea" },
		{ key: "Djebabra", value: "Djebabra" },
		{ key: "Oued El Alleug", value: "Oued El Alleug" },
		{ key: "Benkhelil", value: "Benkhelil" },
		{ key: "Beni-Tamou", value: "Beni-Tamou" },
		{ key: "Chebli", value: "Chebli" },
		{ key: "Bouinan", value: "Bouinan" },
		{ key: "Bouarfa", value: "Bouarfa" },
		{ key: "Blida", value: "Blida" },
	],
	Bouira: [
		{ key: "Ain Laloui", value: "Ain Laloui" },
		{ key: "Hadjera Zerga", value: "Hadjera Zerga" },
		{ key: "Mezdour", value: "Mezdour" },
		{ key: "Taguedite", value: "Taguedite" },
		{ key: "Ridane", value: "Ridane" },
		{ key: "Maamora", value: "Maamora" },
		{ key: "El-Hakimia", value: "El-Hakimia" },
		{ key: "Ahl El Ksar", value: "Ahl El Ksar" },
		{ key: "Dirah", value: "Dirah" },
		{ key: "Dechmia", value: "Dechmia" },
		{ key: "Bechloul", value: "Bechloul" },
		{ key: "Ath Mansour", value: "Ath Mansour" },
		{ key: "Saharidj", value: "Saharidj" },
		{ key: "El Adjiba", value: "El Adjiba" },
		{ key: "El Asnam", value: "El Asnam" },
		{ key: "M Chedallah", value: "M Chedallah" },
		{ key: "Bordj Okhriss", value: "Bordj Okhriss" },
		{ key: "Sour El Ghozlane", value: "Sour El Ghozlane" },
		{ key: "Hanif", value: "Hanif" },
		{ key: "Chorfa", value: "Chorfa" },
		{ key: "Ouled Rached", value: "Ouled Rached" },
		{ key: "Ain El Hadjar", value: "Ain El Hadjar" },
		{ key: "Aghbalou", value: "Aghbalou" },
		{ key: "Raouraoua", value: "Raouraoua" },
		{ key: "El Khabouzia", value: "El Khabouzia" },
		{ key: "Bir Ghbalou", value: "Bir Ghbalou" },
		{ key: "Bouira", value: "Bouira" },
		{ key: "Ain Turk", value: "Ain Turk" },
		{ key: "Ait Laaziz", value: "Ait Laaziz" },
		{ key: "Ain-Bessem", value: "Ain-Bessem" },
		{ key: "El-Mokrani", value: "El-Mokrani" },
		{ key: "Souk El Khemis", value: "Souk El Khemis" },
		{ key: "Aomar", value: "Aomar" },
		{ key: "Djebahia", value: "Djebahia" },
		{ key: "El Hachimia", value: "El Hachimia" },
		{ key: "Haizer", value: "Haizer" },
		{ key: "Taghzout", value: "Taghzout" },
		{ key: "Bouderbala", value: "Bouderbala" },
		{ key: "Boukram", value: "Boukram" },
		{ key: "Guerrouma", value: "Guerrouma" },
		{ key: "Lakhdaria", value: "Lakhdaria" },
		{ key: "Maala", value: "Maala" },
		{ key: "Kadiria", value: "Kadiria" },
		{ key: "Z'barbar (El Isseri )", value: "Z'barbar (El Isseri )" },
		{ key: "Oued El Berdi", value: "Oued El Berdi" },
	],
	Tamanrasset: [
		{ key: "Tazrouk", value: "Tazrouk" },
		{ key: "Abelsa", value: "Abelsa" },
		{ key: "Tamanrasset", value: "Tamanrasset" },
		{ key: "Ain Amguel", value: "Ain Amguel" },
		{ key: "Idles", value: "Idles" },
	],
	Tébessa: [
		{ key: "El-Houidjbet", value: "El-Houidjbet" },
		{ key: "El-Aouinet", value: "El-Aouinet" },
		{ key: "Ferkane", value: "Ferkane" },
		{ key: "Negrine", value: "Negrine" },
		{ key: "Bir Mokkadem", value: "Bir Mokkadem" },
		{ key: "Bir Dheheb", value: "Bir Dheheb" },
		{ key: "Saf Saf El Ouesra", value: "Saf Saf El Ouesra" },
		{ key: "Guorriguer", value: "Guorriguer" },
		{ key: "Bekkaria", value: "Bekkaria" },
		{ key: "Boulhaf Dyr", value: "Boulhaf Dyr" },
		{ key: "Oum Ali", value: "Oum Ali" },
		{ key: "Boukhadra", value: "Boukhadra" },
		{ key: "El Malabiod", value: "El Malabiod" },
		{ key: "Ouenza", value: "Ouenza" },
		{ key: "El Meridj", value: "El Meridj" },
		{ key: "Ain Zerga", value: "Ain Zerga" },
		{ key: "Stah Guentis", value: "Stah Guentis" },
		{ key: "El Ogla", value: "El Ogla" },
		{ key: "El Mezeraa", value: "El Mezeraa" },
		{ key: "Bedjene", value: "Bedjene" },
		{ key: "Morsott", value: "Morsott" },
		{ key: "Telidjen", value: "Telidjen" },
		{ key: "Cheria", value: "Cheria" },
		{ key: "El Ogla El Malha", value: "El Ogla El Malha" },
		{ key: "Bir-El-Ater", value: "Bir-El-Ater" },
		{ key: "Tebessa", value: "Tebessa" },
		{ key: "Hammamet", value: "Hammamet" },
		{ key: "El Kouif", value: "El Kouif" },
	],
	Tlemcen: [
		{ key: "Bab El Assa", value: "Bab El Assa" },
		{ key: "Terny Beni Hediel", value: "Terny Beni Hediel" },
		{ key: "Mansourah", value: "Mansourah" },
		{ key: "Beni Mester", value: "Beni Mester" },
		{ key: "Ain Ghoraba", value: "Ain Ghoraba" },
		{ key: "Chetouane", value: "Chetouane" },
		{ key: "Amieur", value: "Amieur" },
		{ key: "Ain Fezza", value: "Ain Fezza" },
		{ key: "Honnaine", value: "Honnaine" },
		{ key: "Beni Khellad", value: "Beni Khellad" },
		{ key: "Sidi Djillali", value: "Sidi Djillali" },
		{ key: "Bouihi", value: "Bouihi" },
		{ key: "Nedroma", value: "Nedroma" },
		{ key: "M'sirda Fouaga", value: "M'sirda Fouaga" },
		{ key: "Marsa Ben M'hidi", value: "Marsa Ben M'hidi" },
		{ key: "Sidi Medjahed", value: "Sidi Medjahed" },
		{ key: "Beni Boussaid", value: "Beni Boussaid" },
		{ key: "Sebdou", value: "Sebdou" },
		{ key: "El Gor", value: "El Gor" },
		{ key: "El Aricha", value: "El Aricha" },
		{ key: "Bouhlou", value: "Bouhlou" },
		{ key: "Maghnia", value: "Maghnia" },
		{ key: "Hammam Boughrara", value: "Hammam Boughrara" },
		{ key: "Zenata", value: "Zenata" },
		{ key: "Ouled Riyah", value: "Ouled Riyah" },
		{ key: "Hennaya", value: "Hennaya" },
		{ key: "Sidi Abdelli", value: "Sidi Abdelli" },
		{ key: "Souk Tleta", value: "Souk Tleta" },
		{ key: "Bensekrane", value: "Bensekrane" },
		{ key: "Fellaoucene", value: "Fellaoucene" },
		{ key: "Ain Kebira", value: "Ain Kebira" },
		{ key: "Ain Fetah", value: "Ain Fetah" },
		{ key: "Tlemcen", value: "Tlemcen" },
		{ key: "Ain Nehala", value: "Ain Nehala" },
		{ key: "Ain Tellout", value: "Ain Tellout" },
		{ key: "Ain Youcef", value: "Ain Youcef" },
		{ key: "Beni Ouarsous", value: "Beni Ouarsous" },
		{ key: "El Fehoul", value: "El Fehoul" },
		{ key: "Remchi", value: "Remchi" },
		{ key: "Sebbaa Chioukh", value: "Sebbaa Chioukh" },
		{ key: "Souani", value: "Souani" },
		{ key: "Sabra", value: "Sabra" },
		{ key: "Dar Yaghmoracen", value: "Dar Yaghmoracen" },
		{ key: "Ghazaouet", value: "Ghazaouet" },
		{ key: "Souahlia", value: "Souahlia" },
		{ key: "Tianet", value: "Tianet" },
		{ key: "Beni Smiel", value: "Beni Smiel" },
		{ key: "Oued Lakhdar", value: "Oued Lakhdar" },
		{ key: "Ouled Mimoun", value: "Ouled Mimoun" },
		{ key: "Beni Bahdel", value: "Beni Bahdel" },
		{ key: "Beni Snous", value: "Beni Snous" },
		{ key: "Azail", value: "Azail" },
		{ key: "Djebala", value: "Djebala" },
	],
	Tiaret: [
		{ key: "Mahdia", value: "Mahdia" },
		{ key: "Ain Dzarit", value: "Ain Dzarit" },
		{ key: "Sebaine", value: "Sebaine" },
		{ key: "Faidja", value: "Faidja" },
		{ key: "Si Abdelghani", value: "Si Abdelghani" },
		{ key: "Sougueur", value: "Sougueur" },
		{ key: "Tousnina", value: "Tousnina" },
		{ key: "Meghila", value: "Meghila" },
		{ key: "Sebt", value: "Sebt" },
		{ key: "Sidi Hosni", value: "Sidi Hosni" },
		{ key: "Ain El Hadid", value: "Ain El Hadid" },
		{ key: "Frenda", value: "Frenda" },
		{ key: "Takhemaret", value: "Takhemaret" },
		{ key: "Ain Kermes", value: "Ain Kermes" },
		{ key: "Djebilet Rosfa", value: "Djebilet Rosfa" },
		{ key: "Madna", value: "Madna" },
		{ key: "Medrissa", value: "Medrissa" },
		{ key: "Sidi Abderrahmane", value: "Sidi Abderrahmane" },
		{ key: "Ksar Chellala", value: "Ksar Chellala" },
		{ key: "Guertoufa", value: "Guertoufa" },
		{ key: "Serghine", value: "Serghine" },
		{
			key: "Zmalet El Emir Abdelkade",
			value: "Zmalet El Emir Abdelkade",
		},
		{ key: "Oued Lilli", value: "Oued Lilli" },
		{ key: "Sidi Ali Mellal", value: "Sidi Ali Mellal" },
		{ key: "Djillali Ben Amar", value: "Djillali Ben Amar" },
		{ key: "Mechraa Safa", value: "Mechraa Safa" },
		{ key: "Tagdempt", value: "Tagdempt" },
		{ key: "Bougara", value: "Bougara" },
		{ key: "Hamadia", value: "Hamadia" },
		{ key: "Rechaiga", value: "Rechaiga" },
		{ key: "Tidda", value: "Tidda" },
		{ key: "Nadorah", value: "Nadorah" },
		{ key: "Tiaret", value: "Tiaret" },
		{ key: "Medroussa", value: "Medroussa" },
		{ key: "Mellakou", value: "Mellakou" },
		{ key: "Sidi Bakhti", value: "Sidi Bakhti" },
		{ key: "Ain Deheb", value: "Ain Deheb" },
		{ key: "Chehaima", value: "Chehaima" },
		{ key: "Naima", value: "Naima" },
		{ key: "Ain Bouchekif", value: "Ain Bouchekif" },
		{ key: "Dahmouni", value: "Dahmouni" },
		{ key: "Rahouia", value: "Rahouia" },
	],
	"Tizi Ouzou": [
		{ key: "Mizrana", value: "Mizrana" },
		{ key: "Idjeur", value: "Idjeur" },
		{ key: "Beni-Douala", value: "Beni-Douala" },
		{ key: "Beni-Zikki", value: "Beni-Zikki" },
		{ key: "Illoula Oumalou", value: "Illoula Oumalou" },
		{ key: "Agouni-Gueghrane", value: "Agouni-Gueghrane" },
		{ key: "Ait Bouaddou", value: "Ait Bouaddou" },
		{ key: "Ouadhias", value: "Ouadhias" },
		{ key: "Tizi N'tleta", value: "Tizi N'tleta" },
		{ key: "Aghribs", value: "Aghribs" },
		{ key: "Ait-Chafaa", value: "Ait-Chafaa" },
		{ key: "Akerrou", value: "Akerrou" },
		{ key: "Azeffoun", value: "Azeffoun" },
		{ key: "Iflissen", value: "Iflissen" },
		{ key: "Tigzirt", value: "Tigzirt" },
		{ key: "Assi-Youcef", value: "Assi-Youcef" },
		{ key: "Boghni", value: "Boghni" },
		{ key: "Bounouh", value: "Bounouh" },
		{ key: "Mechtras", value: "Mechtras" },
		{ key: "Draa-Ben-Khedda", value: "Draa-Ben-Khedda" },
		{ key: "Sidi Namane", value: "Sidi Namane" },
		{ key: "Tadmait", value: "Tadmait" },
		{ key: "Tirmitine", value: "Tirmitine" },
		{ key: "Ait Boumahdi", value: "Ait Boumahdi" },
		{ key: "Ait-Toudert", value: "Ait-Toudert" },
		{ key: "Beni-Aissi", value: "Beni-Aissi" },
		{ key: "Ouacif", value: "Ouacif" },
		{ key: "Ait Khellili", value: "Ait Khellili" },
		{ key: "Mekla", value: "Mekla" },
		{ key: "Souama", value: "Souama" },
		{ key: "Beni-Yenni", value: "Beni-Yenni" },
		{ key: "Iboudrarene", value: "Iboudrarene" },
		{ key: "Tizi-Ouzou", value: "Tizi-Ouzou" },
		{ key: "Abi-Youcef", value: "Abi-Youcef" },
		{ key: "Ain-El-Hammam", value: "Ain-El-Hammam" },
		{ key: "Ait-Yahia", value: "Ait-Yahia" },
		{ key: "Akbil", value: "Akbil" },
		{ key: "Boudjima", value: "Boudjima" },
		{ key: "Makouda", value: "Makouda" },
		{ key: "Ain-Zaouia", value: "Ain-Zaouia" },
		{ key: "Ait Yahia Moussa", value: "Ait Yahia Moussa" },
		{ key: "Draa-El-Mizan", value: "Draa-El-Mizan" },
		{ key: "Frikat", value: "Frikat" },
		{ key: "M'kira", value: "M'kira" },
		{ key: "Tizi-Gheniff", value: "Tizi-Gheniff" },
		{ key: "Yatafene", value: "Yatafene" },
		{ key: "Illilten", value: "Illilten" },
		{ key: "Imsouhal", value: "Imsouhal" },
		{ key: "Azazga", value: "Azazga" },
		{ key: "Freha", value: "Freha" },
		{ key: "Ifigha", value: "Ifigha" },
		{ key: "Yakourene", value: "Yakourene" },
		{ key: "Zekri", value: "Zekri" },
		{ key: "Ait Aggouacha", value: "Ait Aggouacha" },
		{ key: "Irdjen", value: "Irdjen" },
		{ key: "Larbaa Nath Irathen", value: "Larbaa Nath Irathen" },
		{ key: "Ait-Oumalou", value: "Ait-Oumalou" },
		{ key: "Tizi-Rached", value: "Tizi-Rached" },
		{ key: "Ait-Aissa-Mimoun", value: "Ait-Aissa-Mimoun" },
		{ key: "Ouaguenoun", value: "Ouaguenoun" },
		{ key: "Timizart", value: "Timizart" },
		{ key: "Maatkas", value: "Maatkas" },
		{ key: "Souk-El-Tenine", value: "Souk-El-Tenine" },
		{ key: "Ait-Mahmoud", value: "Ait-Mahmoud" },
		{ key: "Beni Zmenzer", value: "Beni Zmenzer" },
		{ key: "Iferhounene", value: "Iferhounene" },
		{ key: "Bouzeguene", value: "Bouzeguene" },
	],
	Alger: [
		{ key: "Hussein Dey", value: "Hussein Dey" },
		{ key: "Les Eucalyptus", value: "Les Eucalyptus" },
		{ key: "Sidi Moussa", value: "Sidi Moussa" },
		{ key: "Kouba", value: "Kouba" },
		{ key: "Mohamed Belouzdad", value: "Mohamed Belouzdad" },
		{ key: "Ain Taya", value: "Ain Taya" },
		{ key: "Bab Ezzouar", value: "Bab Ezzouar" },
		{ key: "Bordj El Kiffan", value: "Bordj El Kiffan" },
		{ key: "Dar El Beida", value: "Dar El Beida" },
		{ key: "El Marsa", value: "El Marsa" },
		{ key: "Mohammadia", value: "Mohammadia" },
		{ key: "Bir Touta", value: "Bir Touta" },
		{ key: "Ouled Chebel", value: "Ouled Chebel" },
		{ key: "Tessala El Merdja", value: "Tessala El Merdja" },
		{ key: "Herraoua", value: "Herraoua" },
		{ key: "Reghaia", value: "Reghaia" },
		{ key: "Rouiba", value: "Rouiba" },
		{ key: "Maalma", value: "Maalma" },
		{ key: "Rahmania", value: "Rahmania" },
		{ key: "Souidania", value: "Souidania" },
		{ key: "Staoueli", value: "Staoueli" },
		{ key: "Zeralda", value: "Zeralda" },
		{ key: "Baba Hassen", value: "Baba Hassen" },
		{ key: "Douira", value: "Douira" },
		{ key: "Draria", value: "Draria" },
		{ key: "El Achour", value: "El Achour" },
		{ key: "Khraissia", value: "Khraissia" },
		{ key: "Ain Benian", value: "Ain Benian" },
		{ key: "Cheraga", value: "Cheraga" },
		{ key: "Dely Ibrahim", value: "Dely Ibrahim" },
		{ key: "Hammamet", value: "Hammamet" },
		{ key: "Ouled Fayet", value: "Ouled Fayet" },
		{ key: "Alger Centre", value: "Alger Centre" },
		{ key: "El Madania", value: "El Madania" },
		{ key: "El Mouradia", value: "El Mouradia" },
		{ key: "Sidi M'hamed", value: "Sidi M'hamed" },
		{ key: "Sehaoula", value: "Sehaoula" },
		{ key: "Bologhine Ibnou Ziri", value: "Bologhine Ibnou Ziri" },
		{ key: "Casbah", value: "Casbah" },
		{ key: "Oued Koriche", value: "Oued Koriche" },
		{ key: "Rais Hamidou", value: "Rais Hamidou" },
		{ key: "Bir Mourad Rais", value: "Bir Mourad Rais" },
		{ key: "Birkhadem", value: "Birkhadem" },
		{ key: "Djasr Kasentina", value: "Djasr Kasentina" },
		{ key: "Hydra", value: "Hydra" },
		{ key: "El Magharia", value: "El Magharia" },
		{ key: "Ben Aknoun", value: "Ben Aknoun" },
		{ key: "Beni Messous", value: "Beni Messous" },
		{ key: "Bouzareah", value: "Bouzareah" },
		{ key: "El Biar", value: "El Biar" },
		{ key: "Bachedjerah", value: "Bachedjerah" },
		{ key: "Bourouba", value: "Bourouba" },
		{ key: "El Harrach", value: "El Harrach" },
		{ key: "Oued Smar", value: "Oued Smar" },
		{ key: "Baraki", value: "Baraki" },
		{ key: "Bordj El Bahri", value: "Bordj El Bahri" },
		{ key: "Bab El Oued", value: "Bab El Oued" },
	],
	Djelfa: [
		{ key: "Hassi El Euch", value: "Hassi El Euch" },
		{ key: "Ain El Ibel", value: "Ain El Ibel" },
		{ key: "El Guedid", value: "El Guedid" },
		{ key: "Charef", value: "Charef" },
		{ key: "Benyagoub", value: "Benyagoub" },
		{ key: "Sidi Baizid", value: "Sidi Baizid" },
		{ key: "M'liliha", value: "M'liliha" },
		{ key: "Dar Chioukh", value: "Dar Chioukh" },
		{ key: "Taadmit", value: "Taadmit" },
		{ key: "Had Sahary", value: "Had Sahary" },
		{ key: "Bouira Lahdab", value: "Bouira Lahdab" },
		{ key: "Ain Fekka", value: "Ain Fekka" },
		{ key: "Sidi Laadjel", value: "Sidi Laadjel" },
		{ key: "Hassi Fedoul", value: "Hassi Fedoul" },
		{ key: "El Khemis", value: "El Khemis" },
		{ key: "Selmana", value: "Selmana" },
		{ key: "Sed Rahal", value: "Sed Rahal" },
		{ key: "Messaad", value: "Messaad" },
		{ key: "Guettara", value: "Guettara" },
		{ key: "Deldoul", value: "Deldoul" },
		{ key: "Zaccar", value: "Zaccar" },
		{ key: "Douis", value: "Douis" },
		{ key: "El Idrissia", value: "El Idrissia" },
		{ key: "Ain Chouhada", value: "Ain Chouhada" },
		{ key: "Djelfa", value: "Djelfa" },
		{ key: "Birine", value: "Birine" },
		{ key: "Oum Laadham", value: "Oum Laadham" },
		{ key: "Faidh El Botma", value: "Faidh El Botma" },
		{ key: "Amourah", value: "Amourah" },
		{ key: "Zaafrane", value: "Zaafrane" },
		{ key: "Guernini", value: "Guernini" },
		{ key: "Ain Oussera", value: "Ain Oussera" },
		{ key: "Benhar", value: "Benhar" },
		{ key: "Ain Maabed", value: "Ain Maabed" },
		{ key: "Hassi Bahbah", value: "Hassi Bahbah" },
		{ key: "Moudjebara", value: "Moudjebara" },
	],
	Jijel: [
		{ key: "Jijel", value: "Jijel" },
		{ key: "El Aouana", value: "El Aouana" },
		{ key: "Selma Benziada", value: "Selma Benziada" },
		{ key: "Erraguene Souissi", value: "Erraguene Souissi" },
		{ key: "Boussif Ouled Askeur", value: "Boussif Ouled Askeur" },
		{ key: "Ziama Mansouriah", value: "Ziama Mansouriah" },
		{ key: "Chahna", value: "Chahna" },
		{ key: "Emir Abdelkader", value: "Emir Abdelkader" },
		{ key: "Oudjana", value: "Oudjana" },
		{ key: "Taher", value: "Taher" },
		{ key: "Chekfa", value: "Chekfa" },
		{ key: "El Kennar Nouchfi", value: "El Kennar Nouchfi" },
		{ key: "Sidi Abdelaziz", value: "Sidi Abdelaziz" },
		{ key: "El Milia", value: "El Milia" },
		{ key: "Ouled Yahia Khadrouch", value: "Ouled Yahia Khadrouch" },
		{ key: "Ouled Rabah", value: "Ouled Rabah" },
		{ key: "Sidi Marouf", value: "Sidi Marouf" },
		{ key: "Ghebala", value: "Ghebala" },
		{ key: "Settara", value: "Settara" },
		{ key: "Bouraoui Belhadef", value: "Bouraoui Belhadef" },
		{ key: "El Ancer", value: "El Ancer" },
		{ key: "Khiri Oued Adjoul", value: "Khiri Oued Adjoul" },
		{ key: "Djimla", value: "Djimla" },
		{ key: "Kaous", value: "Kaous" },
		{ key: "Texenna", value: "Texenna" },
		{ key: "Bordj T'har", value: "Bordj T'har" },
		{ key: "Boudria Beniyadjis", value: "Boudria Beniyadjis" },
		{ key: "Djemaa Beni Habibi", value: "Djemaa Beni Habibi" },
	],
	Sétif: [
		{ key: "Rosfa", value: "Rosfa" },
		{ key: "Oued El Bared", value: "Oued El Bared" },
		{ key: "Tizi N'bechar", value: "Tizi N'bechar" },
		{ key: "Mezloug", value: "Mezloug" },
		{ key: "Guellal", value: "Guellal" },
		{ key: "Kasr El Abtal", value: "Kasr El Abtal" },
		{ key: "Ouled Si Ahmed", value: "Ouled Si Ahmed" },
		{ key: "Ait Naoual Mezada", value: "Ait Naoual Mezada" },
		{ key: "Ait-Tizi", value: "Ait-Tizi" },
		{ key: "Bouandas", value: "Bouandas" },
		{ key: "Bousselam", value: "Bousselam" },
		{ key: "Hamam Soukhna", value: "Hamam Soukhna" },
		{ key: "Taya", value: "Taya" },
		{ key: "Tella", value: "Tella" },
		{ key: "Ain Oulmene", value: "Ain Oulmene" },
		{ key: "Boutaleb", value: "Boutaleb" },
		{ key: "Hamma", value: "Hamma" },
		{ key: "Ouled Tebben", value: "Ouled Tebben" },
		{ key: "Amoucha", value: "Amoucha" },
		{ key: "Salah Bey", value: "Salah Bey" },
		{ key: "Ain Azel", value: "Ain Azel" },
		{ key: "Ain Lahdjar", value: "Ain Lahdjar" },
		{ key: "Beidha Bordj", value: "Beidha Bordj" },
		{ key: "Bir Haddada", value: "Bir Haddada" },
		{ key: "Guenzet", value: "Guenzet" },
		{ key: "Harbil", value: "Harbil" },
		{ key: "Ain-Roua", value: "Ain-Roua" },
		{ key: "Beni Oussine", value: "Beni Oussine" },
		{ key: "El Ouricia", value: "El Ouricia" },
		{ key: "Bougaa", value: "Bougaa" },
		{ key: "Draa-Kebila", value: "Draa-Kebila" },
		{ key: "Hammam Guergour", value: "Hammam Guergour" },
		{ key: "Setif", value: "Setif" },
		{ key: "Ain El Kebira", value: "Ain El Kebira" },
		{ key: "Dehamcha", value: "Dehamcha" },
		{ key: "Ouled Addouane", value: "Ouled Addouane" },
		{ key: "Ain-Sebt", value: "Ain-Sebt" },
		{ key: "Beni-Aziz", value: "Beni-Aziz" },
		{ key: "Maaouia", value: "Maaouia" },
		{ key: "Bellaa", value: "Bellaa" },
		{ key: "Bir-El-Arch", value: "Bir-El-Arch" },
		{ key: "El-Ouldja", value: "El-Ouldja" },
		{ key: "Tachouda", value: "Tachouda" },
		{ key: "Tala-Ifacene", value: "Tala-Ifacene" },
		{ key: "Serdj-El-Ghoul", value: "Serdj-El-Ghoul" },
		{ key: "Guidjel", value: "Guidjel" },
		{ key: "Ouled Sabor", value: "Ouled Sabor" },
		{ key: "Bazer-Sakra", value: "Bazer-Sakra" },
		{ key: "El Eulma", value: "El Eulma" },
		{ key: "Guelta Zerka", value: "Guelta Zerka" },
		{ key: "Beni Fouda", value: "Beni Fouda" },
		{ key: "Djemila", value: "Djemila" },
		{ key: "Ain-Legradj", value: "Ain-Legradj" },
		{ key: "Beni Chebana", value: "Beni Chebana" },
		{ key: "Beni Ourtilane", value: "Beni Ourtilane" },
		{ key: "Beni-Mouhli", value: "Beni-Mouhli" },
		{ key: "Ain Abessa", value: "Ain Abessa" },
		{ key: "Ain Arnat", value: "Ain Arnat" },
		{ key: "Babor", value: "Babor" },
		{ key: "Maouaklane", value: "Maouaklane" },
	],
	Saïda: [
		{ key: "Saida", value: "Saida" },
		{ key: "Tircine", value: "Tircine" },
		{ key: "Ouled Brahim", value: "Ouled Brahim" },
		{ key: "Ain Soltane", value: "Ain Soltane" },
		{ key: "Maamora", value: "Maamora" },
		{ key: "El Hassasna", value: "El Hassasna" },
		{ key: "Ain Sekhouna", value: "Ain Sekhouna" },
		{ key: "Sidi Boubekeur", value: "Sidi Boubekeur" },
		{ key: "Ouled Khaled", value: "Ouled Khaled" },
		{ key: "Hounet", value: "Hounet" },
		{ key: "Youb", value: "Youb" },
		{ key: "Doui Thabet", value: "Doui Thabet" },
		{ key: "Sidi Ahmed", value: "Sidi Ahmed" },
		{ key: "Moulay Larbi", value: "Moulay Larbi" },
		{ key: "Ain El Hadjar", value: "Ain El Hadjar" },
		{ key: "Sidi Amar", value: "Sidi Amar" },
	],
	Skikda: [
		{ key: "Ain Bouziane", value: "Ain Bouziane" },
		{ key: "Salah Bouchaour", value: "Salah Bouchaour" },
		{ key: "El Hadaiek", value: "El Hadaiek" },
		{ key: "Zerdezas", value: "Zerdezas" },
		{ key: "Ouled Habbaba", value: "Ouled Habbaba" },
		{ key: "Beni Oulbane", value: "Beni Oulbane" },
		{ key: "Sidi Mezghiche", value: "Sidi Mezghiche" },
		{ key: "Beni Bechir", value: "Beni Bechir" },
		{ key: "Ramdane Djamel", value: "Ramdane Djamel" },
		{ key: "Bin El Ouiden", value: "Bin El Ouiden" },
		{ key: "Emjez Edchich", value: "Emjez Edchich" },
		{ key: "Tamalous", value: "Tamalous" },
		{ key: "Ain Kechra", value: "Ain Kechra" },
		{ key: "Ouldja Boulbalout", value: "Ouldja Boulbalout" },
		{ key: "Oum Toub", value: "Oum Toub" },
		{ key: "El Ghedir", value: "El Ghedir" },
		{ key: "Kerkara", value: "Kerkara" },
		{ key: "El Arrouch", value: "El Arrouch" },
		{ key: "Zitouna", value: "Zitouna" },
		{ key: "Ouled Attia", value: "Ouled Attia" },
		{ key: "Oued Zhour", value: "Oued Zhour" },
		{ key: "Collo", value: "Collo" },
		{ key: "Cheraia", value: "Cheraia" },
		{ key: "Beni Zid", value: "Beni Zid" },
		{ key: "Khenag Maoune", value: "Khenag Maoune" },
		{ key: "El Marsa", value: "El Marsa" },
		{ key: "Ben Azzouz", value: "Ben Azzouz" },
		{ key: "Bekkouche Lakhdar", value: "Bekkouche Lakhdar" },
		{ key: "Es Sebt", value: "Es Sebt" },
		{ key: "Ain Charchar", value: "Ain Charchar" },
		{ key: "Azzaba", value: "Azzaba" },
		{ key: "Bouchetata", value: "Bouchetata" },
		{ key: "Filfila", value: "Filfila" },
		{ key: "Hammadi Krouma", value: "Hammadi Krouma" },
		{ key: "Skikda", value: "Skikda" },
		{ key: "Ain Zouit", value: "Ain Zouit" },
		{ key: "Djendel Saadi Mohamed", value: "Djendel Saadi Mohamed" },
		{ key: "Kanoua", value: "Kanoua" },
	],
	"Sidi Bel Abbès": [
		{ key: "Sidi Ali Benyoub", value: "Sidi Ali Benyoub" },
		{ key: "Moulay Slissen", value: "Moulay Slissen" },
		{ key: "El Hacaiba", value: "El Hacaiba" },
		{ key: "Ain Tindamine", value: "Ain Tindamine" },
		{ key: "Tenira", value: "Tenira" },
		{ key: "Oued Sefioun", value: "Oued Sefioun" },
		{ key: "Hassi Dahou", value: "Hassi Dahou" },
		{ key: "Oued Taourira", value: "Oued Taourira" },
		{ key: "Benachiba Chelia", value: "Benachiba Chelia" },
		{ key: "Sidi Yacoub", value: "Sidi Yacoub" },
		{ key: "Sidi Lahcene", value: "Sidi Lahcene" },
		{ key: "Sidi Khaled", value: "Sidi Khaled" },
		{ key: "Tabia", value: "Tabia" },
		{ key: "Sidi Brahim", value: "Sidi Brahim" },
		{ key: "Amarnas", value: "Amarnas" },
		{ key: "Boukhanefis", value: "Boukhanefis" },
		{ key: "Hassi Zahana", value: "Hassi Zahana" },
		{ key: "Chetouane Belaila", value: "Chetouane Belaila" },
		{ key: "Ben Badis", value: "Ben Badis" },
		{ key: "Bedrabine El Mokrani", value: "Bedrabine El Mokrani" },
		{ key: "Sfisef", value: "Sfisef" },
		{ key: "M'cid", value: "M'cid" },
		{ key: "Boudjebaa El Bordj", value: "Boudjebaa El Bordj" },
		{ key: "Ain- Adden", value: "Ain- Adden" },
		{ key: "Sidi Hamadouche", value: "Sidi Hamadouche" },
		{ key: "Sidi Chaib", value: "Sidi Chaib" },
		{ key: "Makedra", value: "Makedra" },
		{ key: "Ain El Berd", value: "Ain El Berd" },
		{ key: "Redjem Demouche", value: "Redjem Demouche" },
		{ key: "Ras El Ma", value: "Ras El Ma" },
		{ key: "Oued Sebaa", value: "Oued Sebaa" },
		{ key: "Marhoum", value: "Marhoum" },
		{ key: "Sidi Bel-Abbes", value: "Sidi Bel-Abbes" },
		{ key: "Ain Thrid", value: "Ain Thrid" },
		{ key: "Sehala Thaoura", value: "Sehala Thaoura" },
		{ key: "Tessala", value: "Tessala" },
		{ key: "Belarbi", value: "Belarbi" },
		{ key: "Mostefa  Ben Brahim", value: "Mostefa  Ben Brahim" },
		{ key: "Tilmouni", value: "Tilmouni" },
		{ key: "Zerouala", value: "Zerouala" },
		{ key: "Dhaya", value: "Dhaya" },
		{ key: "Mezaourou", value: "Mezaourou" },
		{ key: "Teghalimet", value: "Teghalimet" },
		{ key: "Telagh", value: "Telagh" },
		{ key: "Ain Kada", value: "Ain Kada" },
		{ key: "Lamtar", value: "Lamtar" },
		{ key: "Sidi Ali Boussidi", value: "Sidi Ali Boussidi" },
		{ key: "Sidi Dahou Zairs", value: "Sidi Dahou Zairs" },
		{ key: "Bir El Hammam", value: "Bir El Hammam" },
		{ key: "Merine", value: "Merine" },
		{ key: "Tefessour", value: "Tefessour" },
		{ key: "Taoudmout", value: "Taoudmout" },
	],
	Annaba: [
		{ key: "Annaba", value: "Annaba" },
		{ key: "Seraidi", value: "Seraidi" },
		{ key: "Berrahal", value: "Berrahal" },
		{ key: "Oued El Aneb", value: "Oued El Aneb" },
		{ key: "El Hadjar", value: "El Hadjar" },
		{ key: "Sidi Amar", value: "Sidi Amar" },
		{ key: "El Bouni", value: "El Bouni" },
		{ key: "Ain El Berda", value: "Ain El Berda" },
		{ key: "Cheurfa", value: "Cheurfa" },
		{ key: "El Eulma", value: "El Eulma" },
		{ key: "Treat", value: "Treat" },
		{ key: "Chetaibi", value: "Chetaibi" },
	],
	Guelma: [
		{ key: "Nechmaya", value: "Nechmaya" },
		{ key: "Bou Hamdane", value: "Bou Hamdane" },
		{ key: "Hammam Debagh", value: "Hammam Debagh" },
		{ key: "Roknia", value: "Roknia" },
		{ key: "Dahouara", value: "Dahouara" },
		{ key: "Hammam N'bail", value: "Hammam N'bail" },
		{ key: "Guelma", value: "Guelma" },
		{ key: "Boumahra Ahmed", value: "Boumahra Ahmed" },
		{ key: "Ain Ben Beida", value: "Ain Ben Beida" },
		{ key: "Bouchegouf", value: "Bouchegouf" },
		{ key: "Medjez Sfa", value: "Medjez Sfa" },
		{ key: "Oued Ferragha", value: "Oued Ferragha" },
		{ key: "Bouati Mahmoud", value: "Bouati Mahmoud" },
		{ key: "El Fedjoudj", value: "El Fedjoudj" },
		{ key: "Heliopolis", value: "Heliopolis" },
		{ key: "Medjez Amar", value: "Medjez Amar" },
		{ key: "Houari Boumedienne", value: "Houari Boumedienne" },
		{ key: "Ras El Agba", value: "Ras El Agba" },
		{ key: "Sellaoua Announa", value: "Sellaoua Announa" },
		{ key: "Djeballah Khemissi", value: "Djeballah Khemissi" },
		{ key: "Bordj Sabath", value: "Bordj Sabath" },
		{ key: "Oued Zenati", value: "Oued Zenati" },
		{ key: "Ain Regada", value: "Ain Regada" },
		{ key: "Ain Larbi", value: "Ain Larbi" },
		{ key: "Ain Makhlouf", value: "Ain Makhlouf" },
		{ key: "Tamlouka", value: "Tamlouka" },
		{ key: "Ain Sandel", value: "Ain Sandel" },
		{ key: "Bou Hachana", value: "Bou Hachana" },
		{ key: "Khezaras", value: "Khezaras" },
		{ key: "Belkheir", value: "Belkheir" },
		{ key: "Beni Mezline", value: "Beni Mezline" },
		{ key: "Guelaat Bou Sbaa", value: "Guelaat Bou Sbaa" },
		{ key: "Oued Cheham", value: "Oued Cheham" },
		{ key: "Bendjarah", value: "Bendjarah" },
	],
	Constantine: [
		{ key: "Didouche Mourad", value: "Didouche Mourad" },
		{ key: "Hamma Bouziane", value: "Hamma Bouziane" },
		{ key: "Beni Hamidane", value: "Beni Hamidane" },
		{ key: "Zighoud Youcef", value: "Zighoud Youcef" },
		{ key: "Ain Smara", value: "Ain Smara" },
		{ key: "El Khroub", value: "El Khroub" },
		{ key: "Ouled Rahmoun", value: "Ouled Rahmoun" },
		{ key: "Ain Abid", value: "Ain Abid" },
		{ key: "Ben Badis", value: "Ben Badis" },
		{ key: "Ibn Ziad", value: "Ibn Ziad" },
		{ key: "Messaoud Boudjeriou", value: "Messaoud Boudjeriou" },
		{ key: "Constantine", value: "Constantine" },
	],
	Médéa: [
		{ key: "Ouled Hellal", value: "Ouled Hellal" },
		{ key: "Souagui", value: "Souagui" },
		{ key: "Ksar El Boukhari", value: "Ksar El Boukhari" },
		{ key: "M'fatha", value: "M'fatha" },
		{ key: "Saneg", value: "Saneg" },
		{ key: "El Azizia", value: "El Azizia" },
		{ key: "Maghraoua", value: "Maghraoua" },
		{ key: "Mihoub", value: "Mihoub" },
		{ key: "Bouaiche", value: "Bouaiche" },
		{ key: "Boughzoul", value: "Boughzoul" },
		{ key: "Chabounia", value: "Chabounia" },
		{ key: "Hannacha", value: "Hannacha" },
		{ key: "Ouamri", value: "Ouamri" },
		{ key: "Oued Harbil", value: "Oued Harbil" },
		{ key: "Beni Slimane", value: "Beni Slimane" },
		{ key: "Bouaichoune", value: "Bouaichoune" },
		{ key: "Ouled Bouachra", value: "Ouled Bouachra" },
		{ key: "Si Mahdjoub", value: "Si Mahdjoub" },
		{ key: "Bouskene", value: "Bouskene" },
		{ key: "Sidi Rabie", value: "Sidi Rabie" },
		{ key: "Berrouaghia", value: "Berrouaghia" },
		{ key: "Ouled Deid", value: "Ouled Deid" },
		{ key: "Rebaia", value: "Rebaia" },
		{ key: "Medjebar", value: "Medjebar" },
		{ key: "Tletat Ed Douair", value: "Tletat Ed Douair" },
		{ key: "Zoubiria", value: "Zoubiria" },
		{ key: "Aissaouia", value: "Aissaouia" },
		{ key: "El Haoudane", value: "El Haoudane" },
		{ key: "Mezerana", value: "Mezerana" },
		{ key: "Tablat", value: "Tablat" },
		{ key: "Boghar", value: "Boghar" },
		{ key: "Seghouane", value: "Seghouane" },
		{ key: "Draa Esmar", value: "Draa Esmar" },
		{ key: "Medea", value: "Medea" },
		{ key: "Tamesguida", value: "Tamesguida" },
		{ key: "Ben Chicao", value: "Ben Chicao" },
		{ key: "El Hamdania", value: "El Hamdania" },
		{ key: "Ouzera", value: "Ouzera" },
		{ key: "Tizi Mahdi", value: "Tizi Mahdi" },
		{ key: "Ain Boucif", value: "Ain Boucif" },
		{ key: "El Ouinet", value: "El Ouinet" },
		{ key: "Kef Lakhdar", value: "Kef Lakhdar" },
		{ key: "Ouled Emaaraf", value: "Ouled Emaaraf" },
		{ key: "Sidi Demed", value: "Sidi Demed" },
		{ key: "Baata", value: "Baata" },
		{ key: "El Omaria", value: "El Omaria" },
		{ key: "Ouled Brahim", value: "Ouled Brahim" },
		{ key: "Bir Ben Laabed", value: "Bir Ben Laabed" },
		{ key: "El Guelbelkebir", value: "El Guelbelkebir" },
		{ key: "Sedraya", value: "Sedraya" },
		{ key: "Ain Ouksir", value: "Ain Ouksir" },
		{ key: "Chelalet El Adhaoura", value: "Chelalet El Adhaoura" },
		{ key: "Cheniguel", value: "Cheniguel" },
		{ key: "Tafraout", value: "Tafraout" },
		{ key: "Bouchrahil", value: "Bouchrahil" },
		{ key: "Khams Djouamaa", value: "Khams Djouamaa" },
		{ key: "Sidi Naamane", value: "Sidi Naamane" },
		{ key: "Aziz", value: "Aziz" },
		{ key: "Derrag", value: "Derrag" },
		{ key: "Oum El Djellil", value: "Oum El Djellil" },
		{ key: "Djouab", value: "Djouab" },
		{ key: "Sidi Zahar", value: "Sidi Zahar" },
		{ key: "Sidi Ziane", value: "Sidi Ziane" },
		{ key: "Ouled Antar", value: "Ouled Antar" },
	],
	Mostaganem: [
		{ key: "Fornaka", value: "Fornaka" },
		{ key: "Oued El Kheir", value: "Oued El Kheir" },
		{ key: "Hassiane", value: "Hassiane" },
		{ key: "Hassi Mameche", value: "Hassi Mameche" },
		{ key: "Mazagran", value: "Mazagran" },
		{ key: "Stidia", value: "Stidia" },
		{ key: "Ain-Tedles", value: "Ain-Tedles" },
		{ key: "Sidi Belaattar", value: "Sidi Belaattar" },
		{ key: "Sour", value: "Sour" },
		{ key: "Ain-Boudinar", value: "Ain-Boudinar" },
		{ key: "Kheir-Eddine", value: "Kheir-Eddine" },
		{ key: "Sayada", value: "Sayada" },
		{ key: "Sidi Ali", value: "Sidi Ali" },
		{ key: "Tazgait", value: "Tazgait" },
		{ key: "Benabdelmalek Ramdane", value: "Benabdelmalek Ramdane" },
		{ key: "Mostaganem", value: "Mostaganem" },
		{ key: "Hadjadj", value: "Hadjadj" },
		{ key: "Sidi-Lakhdar", value: "Sidi-Lakhdar" },
		{ key: "Achaacha", value: "Achaacha" },
		{ key: "Khadra", value: "Khadra" },
		{ key: "Nekmaria", value: "Nekmaria" },
		{ key: "Ouled Boughalem", value: "Ouled Boughalem" },
		{ key: "Bouguirat", value: "Bouguirat" },
		{ key: "Safsaf", value: "Safsaf" },
		{ key: "Sirat", value: "Sirat" },
		{ key: "Souaflia", value: "Souaflia" },
		{ key: "Ain-Sidi Cherif", value: "Ain-Sidi Cherif" },
		{ key: "Mansourah", value: "Mansourah" },
		{ key: "Mesra", value: "Mesra" },
		{ key: "Touahria", value: "Touahria" },
		{ key: "Ain-Nouissy", value: "Ain-Nouissy" },
		{ key: "Ouled-Maalah", value: "Ouled-Maalah" },
	],
	"M'Sila": [
		{ key: "Chellal", value: "Chellal" },
		{ key: "Ouled Madhi", value: "Ouled Madhi" },
		{ key: "Khettouti Sed-El-Jir", value: "Khettouti Sed-El-Jir" },
		{ key: "Belaiba", value: "Belaiba" },
		{ key: "Berhoum", value: "Berhoum" },
		{ key: "Dehahna", value: "Dehahna" },
		{ key: "Magra", value: "Magra" },
		{ key: "Beni Ilmane", value: "Beni Ilmane" },
		{ key: "Bouti Sayeh", value: "Bouti Sayeh" },
		{ key: "Sidi Aissa", value: "Sidi Aissa" },
		{ key: "Ain El Hadjel", value: "Ain El Hadjel" },
		{ key: "Sidi Hadjeres", value: "Sidi Hadjeres" },
		{ key: "Bou Saada", value: "Bou Saada" },
		{ key: "El Hamel", value: "El Hamel" },
		{ key: "Oulteme", value: "Oulteme" },
		{ key: "Benzouh", value: "Benzouh" },
		{ key: "Ouled Sidi Brahim", value: "Ouled Sidi Brahim" },
		{ key: "Sidi Ameur", value: "Sidi Ameur" },
		{ key: "Tamsa", value: "Tamsa" },
		{ key: "Ben Srour", value: "Ben Srour" },
		{ key: "Mohamed Boudiaf", value: "Mohamed Boudiaf" },
		{ key: "Ouled Slimane", value: "Ouled Slimane" },
		{ key: "Zarzour", value: "Zarzour" },
		{ key: "Ain El Melh", value: "Ain El Melh" },
		{ key: "Ain Fares", value: "Ain Fares" },
		{ key: "Ain Rich", value: "Ain Rich" },
		{ key: "Bir Foda", value: "Bir Foda" },
		{ key: "Sidi M'hamed", value: "Sidi M'hamed" },
		{ key: "Medjedel", value: "Medjedel" },
		{ key: "Menaa", value: "Menaa" },
		{ key: "Djebel Messaad", value: "Djebel Messaad" },
		{ key: "Slim", value: "Slim" },
		{ key: "M'sila", value: "M'sila" },
		{ key: "Hammam Dalaa", value: "Hammam Dalaa" },
		{ key: "Ouanougha", value: "Ouanougha" },
		{ key: "Ouled Mansour", value: "Ouled Mansour" },
		{ key: "Tarmount", value: "Tarmount" },
		{ key: "Maadid", value: "Maadid" },
		{ key: "M'tarfa", value: "M'tarfa" },
		{ key: "Maarif", value: "Maarif" },
		{ key: "Ouled Derradj", value: "Ouled Derradj" },
		{ key: "Souamaa", value: "Souamaa" },
		{ key: "El Houamed", value: "El Houamed" },
		{ key: "Khoubana", value: "Khoubana" },
		{ key: "M'cif", value: "M'cif" },
		{ key: "Ain Khadra", value: "Ain Khadra" },
		{ key: "Ouled Addi Guebala", value: "Ouled Addi Guebala" },
	],
	Mascara: [
		{ key: "Oued El Abtal", value: "Oued El Abtal" },
		{ key: "Sidi Abdelmoumene", value: "Sidi Abdelmoumene" },
		{ key: "Sedjerara", value: "Sedjerara" },
		{ key: "Mohammadia", value: "Mohammadia" },
		{ key: "Tighennif", value: "Tighennif" },
		{ key: "Mocta-Douz", value: "Mocta-Douz" },
		{ key: "Ferraguig", value: "Ferraguig" },
		{ key: "El Ghomri", value: "El Ghomri" },
		{ key: "Zahana", value: "Zahana" },
		{ key: "El Gaada", value: "El Gaada" },
		{ key: "Ras El Ain Amirouche", value: "Ras El Ain Amirouche" },
		{ key: "Oggaz", value: "Oggaz" },
		{ key: "Alaimia", value: "Alaimia" },
		{ key: "Sig", value: "Sig" },
		{ key: "Chorfa", value: "Chorfa" },
		{ key: "Bou Henni", value: "Bou Henni" },
		{ key: "El Mamounia", value: "El Mamounia" },
		{ key: "El Gueitena", value: "El Gueitena" },
		{ key: "Ain Fares", value: "Ain Fares" },
		{ key: "Gharrous", value: "Gharrous" },
		{ key: "Benian", value: "Benian" },
		{ key: "Aouf", value: "Aouf" },
		{ key: "Guerdjoum", value: "Guerdjoum" },
		{ key: "Ain Frass", value: "Ain Frass" },
		{ key: "Ain Fekan", value: "Ain Fekan" },
		{ key: "Khalouia", value: "Khalouia" },
		{ key: "El Menaouer", value: "El Menaouer" },
		{ key: "El Bordj", value: "El Bordj" },
		{ key: "Sidi Boussaid", value: "Sidi Boussaid" },
		{ key: "Matemore", value: "Matemore" },
		{ key: "Sidi Kada", value: "Sidi Kada" },
		{ key: "Makhda", value: "Makhda" },
		{ key: "Mascara", value: "Mascara" },
		{ key: "Bouhanifia", value: "Bouhanifia" },
		{ key: "Ghriss", value: "Ghriss" },
		{ key: "Hacine", value: "Hacine" },
		{ key: "El Keurt", value: "El Keurt" },
		{ key: "Froha", value: "Froha" },
		{ key: "Tizi", value: "Tizi" },
		{ key: "Sehailia", value: "Sehailia" },
		{ key: "Maoussa", value: "Maoussa" },
		{ key: "Sidi Abdeldjebar", value: "Sidi Abdeldjebar" },
		{ key: "El Hachem", value: "El Hachem" },
		{ key: "Nesmot", value: "Nesmot" },
		{ key: "Zelamta", value: "Zelamta" },
		{ key: "Ain Ferah", value: "Ain Ferah" },
		{ key: "Oued Taria", value: "Oued Taria" },
	],
	Ouargla: [
		{ key: "Ouargla", value: "Ouargla" },
		{ key: "Hassi Messaoud", value: "Hassi Messaoud" },
		{ key: "Ain Beida", value: "Ain Beida" },
		{ key: "Hassi Ben Abdellah", value: "Hassi Ben Abdellah" },
		{ key: "Sidi Khouiled", value: "Sidi Khouiled" },
		{ key: "El Borma", value: "El Borma" },
		{ key: "Rouissat", value: "Rouissat" },
		{ key: "N'goussa", value: "N'goussa" },
	],
	Oran: [
		{ key: "Sidi Chami", value: "Sidi Chami" },
		{ key: "Hassi Mefsoukh", value: "Hassi Mefsoukh" },
		{ key: "Bir El Djir", value: "Bir El Djir" },
		{ key: "Hassi Ben Okba", value: "Hassi Ben Okba" },
		{ key: "Gdyel", value: "Gdyel" },
		{ key: "Hassi Bounif", value: "Hassi Bounif" },
		{ key: "El Kerma", value: "El Kerma" },
		{ key: "Es Senia", value: "Es Senia" },
		{ key: "Ben Freha", value: "Ben Freha" },
		{ key: "Arzew", value: "Arzew" },
		{ key: "Sidi Ben Yebka", value: "Sidi Ben Yebka" },
		{ key: "Ain Biya", value: "Ain Biya" },
		{ key: "Bethioua", value: "Bethioua" },
		{ key: "Marsat El Hadjadj", value: "Marsat El Hadjadj" },
		{ key: "Ain Turk", value: "Ain Turk" },
		{ key: "Oran", value: "Oran" },
		{ key: "El Ancor", value: "El Ancor" },
		{ key: "Mers El Kebir", value: "Mers El Kebir" },
		{ key: "Boufatis", value: "Boufatis" },
		{ key: "El Braya", value: "El Braya" },
		{ key: "Oued Tlelat", value: "Oued Tlelat" },
		{ key: "Ain Kerma", value: "Ain Kerma" },
		{ key: "Boutlelis", value: "Boutlelis" },
		{ key: "Messerghin", value: "Messerghin" },
		{ key: "Bousfer", value: "Bousfer" },
		{ key: "Tafraoui", value: "Tafraoui" },
	],
	"El Bayadh": [
		{ key: "Ain El Orak", value: "Ain El Orak" },
		{ key: "Krakda", value: "Krakda" },
		{ key: "Sidi Slimane", value: "Sidi Slimane" },
		{ key: "Sidi Ameur", value: "Sidi Ameur" },
		{ key: "Boualem", value: "Boualem" },
		{ key: "El Bnoud", value: "El Bnoud" },
		{ key: "Bougtoub", value: "Bougtoub" },
		{ key: "El Kheiter", value: "El Kheiter" },
		{ key: "Tousmouline", value: "Tousmouline" },
		{ key: "Sidi Tiffour", value: "Sidi Tiffour" },
		{ key: "Stitten", value: "Stitten" },
		{ key: "El Bayadh", value: "El Bayadh" },
		{ key: "Rogassa", value: "Rogassa" },
		{ key: "El Mehara", value: "El Mehara" },
		{ key: "Kef El Ahmar", value: "Kef El Ahmar" },
		{ key: "Brezina", value: "Brezina" },
		{ key: "Ghassoul", value: "Ghassoul" },
		{ key: "Labiodh Sidi Cheikh", value: "Labiodh Sidi Cheikh" },
		{ key: "Boussemghoun", value: "Boussemghoun" },
		{ key: "Cheguig", value: "Cheguig" },
		{ key: "Chellala", value: "Chellala" },
		{ key: "Arbaouat", value: "Arbaouat" },
	],
	Illizi: [
		{ key: "Bordj Omar Driss", value: "Bordj Omar Driss" },
		{ key: "Debdeb", value: "Debdeb" },
		{ key: "In Amenas", value: "In Amenas" },
		{ key: "Illizi", value: "Illizi" },
	],
	"Bordj Bou Arreridj": [
		{ key: "Elhammadia", value: "Elhammadia" },
		{ key: "Ouled Sidi-Brahim", value: "Ouled Sidi-Brahim" },
		{ key: "Ain Taghrout", value: "Ain Taghrout" },
		{ key: "Tixter", value: "Tixter" },
		{ key: "Belimour", value: "Belimour" },
		{ key: "El Annasseur", value: "El Annasseur" },
		{ key: "Ghailasa", value: "Ghailasa" },
		{ key: "Taglait", value: "Taglait" },
		{ key: "Bordj Ghedir", value: "Bordj Ghedir" },
		{ key: "El Euch", value: "El Euch" },
		{ key: "Sidi-Embarek", value: "Sidi-Embarek" },
		{ key: "Khelil", value: "Khelil" },
		{ key: "Bir Kasdali", value: "Bir Kasdali" },
		{ key: "Tefreg", value: "Tefreg" },
		{ key: "El Main", value: "El Main" },
		{ key: "Djaafra", value: "Djaafra" },
		{ key: "Colla", value: "Colla" },
		{ key: "Teniet En Nasr", value: "Teniet En Nasr" },
		{ key: "El M'hir", value: "El M'hir" },
		{ key: "Ksour", value: "Ksour" },
		{ key: "Mansoura", value: "Mansoura" },
		{ key: "Haraza", value: "Haraza" },
		{ key: "Rabta", value: "Rabta" },
		{ key: "El Achir", value: "El Achir" },
		{ key: "Hasnaoua", value: "Hasnaoua" },
		{ key: "Medjana", value: "Medjana" },
		{ key: "Ain Tesra", value: "Ain Tesra" },
		{ key: "Ouled Brahem", value: "Ouled Brahem" },
		{ key: "Ras El Oued", value: "Ras El Oued" },
		{ key: "Bordj Zemmoura", value: "Bordj Zemmoura" },
		{ key: "Ouled Dahmane", value: "Ouled Dahmane" },
		{ key: "Tassamert", value: "Tassamert" },
		{ key: "B. B. Arreridj", value: "B. B. Arreridj" },
		{ key: "Ben Daoud", value: "Ben Daoud" },
	],
	Boumerdès: [
		{ key: "El Kharrouba", value: "El Kharrouba" },
		{ key: "Dellys", value: "Dellys" },
		{ key: "Ben Choud", value: "Ben Choud" },
		{ key: "Afir", value: "Afir" },
		{ key: "Thenia", value: "Thenia" },
		{ key: "Beni Amrane", value: "Beni Amrane" },
		{ key: "Khemis El Khechna", value: "Khemis El Khechna" },
		{ key: "Ammal", value: "Ammal" },
		{ key: "Timezrit", value: "Timezrit" },
		{ key: "Zemmouri", value: "Zemmouri" },
		{ key: "Larbatache", value: "Larbatache" },
		{ key: "Isser", value: "Isser" },
		{ key: "Chabet El Ameur", value: "Chabet El Ameur" },
		{ key: "Ouled Aissa", value: "Ouled Aissa" },
		{ key: "Naciria", value: "Naciria" },
		{ key: "Bouzegza Keddara", value: "Bouzegza Keddara" },
		{ key: "Souk El Had", value: "Souk El Had" },
		{ key: "Sidi Daoud", value: "Sidi Daoud" },
		{ key: "Baghlia", value: "Baghlia" },
		{ key: "Leghata", value: "Leghata" },
		{ key: "Djinet", value: "Djinet" },
		{ key: "Tidjelabine", value: "Tidjelabine" },
		{ key: "Si Mustapha", value: "Si Mustapha" },
		{ key: "Ouled Hedadj", value: "Ouled Hedadj" },
		{ key: "Ouled Moussa", value: "Ouled Moussa" },
		{ key: "Boumerdes", value: "Boumerdes" },
		{ key: "Corso", value: "Corso" },
		{ key: "Bordj Menaiel", value: "Bordj Menaiel" },
		{ key: "Boudouaou", value: "Boudouaou" },
		{ key: "Boudouaou El Bahri", value: "Boudouaou El Bahri" },
		{ key: "Taourga", value: "Taourga" },
		{ key: "Hammedi", value: "Hammedi" },
	],
	"El Tarf": [
		{ key: "Ain El Assel", value: "Ain El Assel" },
		{ key: "Bougous", value: "Bougous" },
		{ key: "El Tarf", value: "El Tarf" },
		{ key: "Zitouna", value: "Zitouna" },
		{ key: "Besbes", value: "Besbes" },
		{ key: "Ain Kerma", value: "Ain Kerma" },
		{ key: "Bouhadjar", value: "Bouhadjar" },
		{ key: "Hammam Beni Salah", value: "Hammam Beni Salah" },
		{ key: "Oued Zitoun", value: "Oued Zitoun" },
		{ key: "Ben M Hidi", value: "Ben M Hidi" },
		{ key: "Berrihane", value: "Berrihane" },
		{ key: "Chebaita Mokhtar", value: "Chebaita Mokhtar" },
		{ key: "Echatt", value: "Echatt" },
		{ key: "El Aioun", value: "El Aioun" },
		{ key: "El Kala", value: "El Kala" },
		{ key: "Souarekh", value: "Souarekh" },
		{ key: "Zerizer", value: "Zerizer" },
		{ key: "Bouteldja", value: "Bouteldja" },
		{ key: "Chefia", value: "Chefia" },
		{ key: "Lac Des Oiseaux", value: "Lac Des Oiseaux" },
		{ key: "Chihani", value: "Chihani" },
		{ key: "Raml Souk", value: "Raml Souk" },
		{ key: "Asfour", value: "Asfour" },
		{ key: "Drean", value: "Drean" },
	],
	Tindouf: [
		{ key: "Tindouf", value: "Tindouf" },
		{ key: "Oum El Assel", value: "Oum El Assel" },
	],
	Tissemsilt: [
		{ key: "Khemisti", value: "Khemisti" },
		{ key: "Theniet El Had", value: "Theniet El Had" },
		{ key: "Ouled Bessam", value: "Ouled Bessam" },
		{ key: "Sidi Boutouchent", value: "Sidi Boutouchent" },
		{ key: "Tissemsilt", value: "Tissemsilt" },
		{ key: "Sidi Lantri", value: "Sidi Lantri" },
		{ key: "Beni Chaib", value: "Beni Chaib" },
		{ key: "Beni Lahcene", value: "Beni Lahcene" },
		{ key: "Sidi Abed", value: "Sidi Abed" },
		{ key: "Sidi Slimane", value: "Sidi Slimane" },
		{ key: "Boucaid", value: "Boucaid" },
		{ key: "Larbaa", value: "Larbaa" },
		{ key: "Lazharia", value: "Lazharia" },
		{ key: "Lardjem", value: "Lardjem" },
		{ key: "Melaab", value: "Melaab" },
		{ key: "Layoune", value: "Layoune" },
		{ key: "Tamellahet", value: "Tamellahet" },
		{ key: "Youssoufia", value: "Youssoufia" },
		{
			key: "Bordj El Emir Abdelkader",
			value: "Bordj El Emir Abdelkader",
		},
		{ key: "Ammari", value: "Ammari" },
		{ key: "Maacem", value: "Maacem" },
		{ key: "Bordj Bounaama", value: "Bordj Bounaama" },
	],
	"El Oued": [
		{ key: "Douar El Maa", value: "Douar El Maa" },
		{ key: "El Ogla", value: "El Ogla" },
		{ key: "Magrane", value: "Magrane" },
		{ key: "Sidi Aoun", value: "Sidi Aoun" },
		{ key: "Mih Ouansa", value: "Mih Ouansa" },
		{ key: "Kouinine", value: "Kouinine" },
		{ key: "Bayadha", value: "Bayadha" },
		{ key: "Nakhla", value: "Nakhla" },
		{ key: "Robbah", value: "Robbah" },
		{ key: "Guemar", value: "Guemar" },
		{ key: "Ben Guecha", value: "Ben Guecha" },
		{ key: "Ourmes", value: "Ourmes" },
		{ key: "Taghzout", value: "Taghzout" },
		{ key: "Hamraia", value: "Hamraia" },
		{ key: "Reguiba", value: "Reguiba" },
		{ key: "Debila", value: "Debila" },
		{ key: "Hassani Abdelkrim", value: "Hassani Abdelkrim" },
		{ key: "Hassi Khalifa", value: "Hassi Khalifa" },
		{ key: "Trifaoui", value: "Trifaoui" },
		{ key: "Taleb Larbi", value: "Taleb Larbi" },
		{ key: "Oued El Alenda", value: "Oued El Alenda" },
		{ key: "El-Oued", value: "El-Oued" },
	],
	Khenchela: [
		{ key: "Khirane", value: "Khirane" },
		{ key: "Babar", value: "Babar" },
		{ key: "El Mahmal", value: "El Mahmal" },
		{ key: "Ouled Rechache", value: "Ouled Rechache" },
		{ key: "Djellal", value: "Djellal" },
		{ key: "Yabous", value: "Yabous" },
		{ key: "Khenchela", value: "Khenchela" },
		{ key: "Kais", value: "Kais" },
		{ key: "Chelia", value: "Chelia" },
		{ key: "Remila", value: "Remila" },
		{ key: "Taouzianat", value: "Taouzianat" },
		{ key: "Baghai", value: "Baghai" },
		{ key: "El Hamma", value: "El Hamma" },
		{ key: "Ensigha", value: "Ensigha" },
		{ key: "Tamza", value: "Tamza" },
		{ key: "Ain Touila", value: "Ain Touila" },
		{ key: "M'toussa", value: "M'toussa" },
		{ key: "Bouhmama", value: "Bouhmama" },
		{ key: "El Oueldja", value: "El Oueldja" },
		{ key: "M'sara", value: "M'sara" },
		{ key: "Chechar", value: "Chechar" },
	],
	"Souk Ahras": [
		{ key: "Souk Ahras", value: "Souk Ahras" },
		{ key: "Ain Soltane", value: "Ain Soltane" },
		{ key: "Sedrata", value: "Sedrata" },
		{ key: "Hanencha", value: "Hanencha" },
		{ key: "Machroha", value: "Machroha" },
		{ key: "Ain Zana", value: "Ain Zana" },
		{ key: "Ouled Driss", value: "Ouled Driss" },
		{ key: "Terraguelt", value: "Terraguelt" },
		{ key: "Oum El Adhaim", value: "Oum El Adhaim" },
		{ key: "Oued Kebrit", value: "Oued Kebrit" },
		{ key: "Tiffech", value: "Tiffech" },
		{ key: "Ragouba", value: "Ragouba" },
		{ key: "Drea", value: "Drea" },
		{ key: "Taoura", value: "Taoura" },
		{ key: "Zaarouria", value: "Zaarouria" },
		{ key: "Haddada", value: "Haddada" },
		{ key: "Khedara", value: "Khedara" },
		{ key: "Ouled Moumen", value: "Ouled Moumen" },
		{ key: "Merahna", value: "Merahna" },
		{ key: "Ouillen", value: "Ouillen" },
		{ key: "Sidi Fredj", value: "Sidi Fredj" },
		{ key: "Bir Bouhouche", value: "Bir Bouhouche" },
		{ key: "Safel El Ouiden", value: "Safel El Ouiden" },
		{ key: "Khemissa", value: "Khemissa" },
		{ key: "M'daourouche", value: "M'daourouche" },
		{ key: "Zouabi", value: "Zouabi" },
	],
	Tipaza: [
		{ key: "Hadjout", value: "Hadjout" },
		{ key: "Merad", value: "Merad" },
		{ key: "Menaceur", value: "Menaceur" },
		{ key: "Aghbal", value: "Aghbal" },
		{ key: "Nador", value: "Nador" },
		{ key: "Sidi-Amar", value: "Sidi-Amar" },
		{ key: "Gouraya", value: "Gouraya" },
		{ key: "Messelmoun", value: "Messelmoun" },
		{ key: "Cherchell", value: "Cherchell" },
		{ key: "Hadjret Ennous", value: "Hadjret Ennous" },
		{ key: "Sidi Ghiles", value: "Sidi Ghiles" },
		{ key: "Damous", value: "Damous" },
		{ key: "Larhat", value: "Larhat" },
		{ key: "Fouka", value: "Fouka" },
		{ key: "Ain Tagourait", value: "Ain Tagourait" },
		{ key: "Bou Haroun", value: "Bou Haroun" },
		{ key: "Bou Ismail", value: "Bou Ismail" },
		{ key: "Khemisti", value: "Khemisti" },
		{ key: "Ahmer El Ain", value: "Ahmer El Ain" },
		{ key: "Bourkika", value: "Bourkika" },
		{ key: "Douaouda", value: "Douaouda" },
		{ key: "Sidi Rached", value: "Sidi Rached" },
		{ key: "Attatba", value: "Attatba" },
		{ key: "Chaiba", value: "Chaiba" },
		{ key: "Kolea", value: "Kolea" },
		{ key: "Sidi Semiane", value: "Sidi Semiane" },
		{ key: "Tipaza", value: "Tipaza" },
		{ key: "Beni Mileuk", value: "Beni Mileuk" },
	],
	Mila: [
		{ key: "El Mechira", value: "El Mechira" },
		{ key: "El Ayadi Barbes", value: "El Ayadi Barbes" },
		{ key: "Ain Beida Harriche", value: "Ain Beida Harriche" },
		{ key: "Tassala Lematai", value: "Tassala Lematai" },
		{ key: "Terrai Bainen", value: "Terrai Bainen" },
		{ key: "Amira Arres", value: "Amira Arres" },
		{ key: "Tassadane Haddada", value: "Tassadane Haddada" },
		{ key: "Minar Zarza", value: "Minar Zarza" },
		{ key: "Sidi Merouane", value: "Sidi Merouane" },
		{ key: "Chigara", value: "Chigara" },
		{ key: "Hamala", value: "Hamala" },
		{ key: "Grarem Gouga", value: "Grarem Gouga" },
		{ key: "Tiberguent", value: "Tiberguent" },
		{ key: "Rouached", value: "Rouached" },
		{ key: "Derrahi Bousselah", value: "Derrahi Bousselah" },
		{ key: "Zeghaia", value: "Zeghaia" },
		{ key: "Oued Endja", value: "Oued Endja" },
		{ key: "Ahmed Rachedi", value: "Ahmed Rachedi" },
		{ key: "Tadjenanet", value: "Tadjenanet" },
		{ key: "Ain Mellouk", value: "Ain Mellouk" },
		{ key: "Ouled Khalouf", value: "Ouled Khalouf" },
		{ key: "Benyahia Abderrahmane", value: "Benyahia Abderrahmane" },
		{ key: "Teleghma", value: "Teleghma" },
		{ key: "Oued Seguen", value: "Oued Seguen" },
		{ key: "Oued Athmenia", value: "Oued Athmenia" },
		{ key: "Ain Tine", value: "Ain Tine" },
		{ key: "Chelghoum Laid", value: "Chelghoum Laid" },
		{ key: "Yahia Beniguecha", value: "Yahia Beniguecha" },
		{ key: "Ferdjioua", value: "Ferdjioua" },
		{ key: "Sidi Khelifa", value: "Sidi Khelifa" },
		{ key: "Mila", value: "Mila" },
		{ key: "Bouhatem", value: "Bouhatem" },
	],
	"Aïn Defla": [
		{ key: "Khemis-Miliana", value: "Khemis-Miliana" },
		{ key: "Sidi-Lakhdar", value: "Sidi-Lakhdar" },
		{ key: "Ain-Benian", value: "Ain-Benian" },
		{ key: "Ain-Torki", value: "Ain-Torki" },
		{ key: "Hammam-Righa", value: "Hammam-Righa" },
		{ key: "Bourached", value: "Bourached" },
		{ key: "Hoceinia", value: "Hoceinia" },
		{ key: "Djelida", value: "Djelida" },
		{ key: "Arib", value: "Arib" },
		{ key: "Djemaa Ouled Cheikh", value: "Djemaa Ouled Cheikh" },
		{ key: "El-Amra", value: "El-Amra" },
		{ key: "El-Attaf", value: "El-Attaf" },
		{ key: "Tiberkanine", value: "Tiberkanine" },
		{ key: "Ain-Bouyahia", value: "Ain-Bouyahia" },
		{ key: "El-Abadia", value: "El-Abadia" },
		{ key: "Tacheta Zegagha", value: "Tacheta Zegagha" },
		{ key: "Birbouche", value: "Birbouche" },
		{ key: "Djendel", value: "Djendel" },
		{ key: "Ben Allal", value: "Ben Allal" },
		{ key: "Oued Chorfa", value: "Oued Chorfa" },
		{ key: "Boumedfaa", value: "Boumedfaa" },
		{ key: "Ain-Lechiakh", value: "Ain-Lechiakh" },
		{ key: "Ain-Soltane", value: "Ain-Soltane" },
		{ key: "Oued Djemaa", value: "Oued Djemaa" },
		{ key: "El-Maine", value: "El-Maine" },
		{ key: "Rouina", value: "Rouina" },
		{ key: "Zeddine", value: "Zeddine" },
		{ key: "Bir-Ould-Khelifa", value: "Bir-Ould-Khelifa" },
		{ key: "Bordj-Emir-Khaled", value: "Bordj-Emir-Khaled" },
		{ key: "Tarik-Ibn-Ziad", value: "Tarik-Ibn-Ziad" },
		{ key: "Bathia", value: "Bathia" },
		{ key: "Belaas", value: "Belaas" },
		{ key: "Hassania", value: "Hassania" },
		{ key: "Ain-Defla", value: "Ain-Defla" },
		{ key: "Miliana", value: "Miliana" },
		{ key: "Mekhatria", value: "Mekhatria" },
	],
	Naâma: [
		{ key: "Tiout", value: "Tiout" },
		{ key: "Moghrar", value: "Moghrar" },
		{ key: "Asla", value: "Asla" },
		{ key: "Kasdir", value: "Kasdir" },
		{ key: "Makmen Ben Amar", value: "Makmen Ben Amar" },
		{ key: "Ain Sefra", value: "Ain Sefra" },
		{ key: "Mecheria", value: "Mecheria" },
		{ key: "El Biodh", value: "El Biodh" },
		{ key: "Ain Ben Khelil", value: "Ain Ben Khelil" },
		{ key: "Naama", value: "Naama" },
		{ key: "Djenienne Bourezg", value: "Djenienne Bourezg" },
		{ key: "Sfissifa", value: "Sfissifa" },
	],
	"Aïn Témouchent": [
		{ key: "Sidi Boumediene", value: "Sidi Boumediene" },
		{ key: "Tamzoura", value: "Tamzoura" },
		{ key: "Chaabat El Ham", value: "Chaabat El Ham" },
		{ key: "El Maleh", value: "El Maleh" },
		{ key: "Ouled Kihal", value: "Ouled Kihal" },
		{ key: "Chentouf", value: "Chentouf" },
		{ key: "Terga", value: "Terga" },
		{ key: "Oued Sebbah", value: "Oued Sebbah" },
		{ key: "El Amria", value: "El Amria" },
		{ key: "Hassi El Ghella", value: "Hassi El Ghella" },
		{ key: "Ouled Boudjemaa", value: "Ouled Boudjemaa" },
		{ key: "Aghlal", value: "Aghlal" },
		{ key: "Ain Kihal", value: "Ain Kihal" },
		{ key: "Ain Tolba", value: "Ain Tolba" },
		{ key: "Aoubellil", value: "Aoubellil" },
		{ key: "Beni Saf", value: "Beni Saf" },
		{ key: "Hassasna", value: "Hassasna" },
		{ key: "Emir Abdelkader", value: "Emir Abdelkader" },
		{ key: "Sidi Safi", value: "Sidi Safi" },
		{ key: "Oulhaca El Gheraba", value: "Oulhaca El Gheraba" },
		{ key: "Sidi Ouriache", value: "Sidi Ouriache" },
		{ key: "Ain El Arbaa", value: "Ain El Arbaa" },
		{ key: "El Messaid", value: "El Messaid" },
		{ key: "Oued Berkeche", value: "Oued Berkeche" },
		{ key: "Sidi Ben Adda", value: "Sidi Ben Adda" },
		{ key: "Ain Temouchent", value: "Ain Temouchent" },
		{ key: "Bouzedjar", value: "Bouzedjar" },
		{ key: "Hammam Bou Hadjar", value: "Hammam Bou Hadjar" },
	],
	Ghardaïa: [
		{ key: "Dhayet Bendhahoua", value: "Dhayet Bendhahoua" },
		{ key: "Mansoura", value: "Mansoura" },
		{ key: "El Atteuf", value: "El Atteuf" },
		{ key: "Bounoura", value: "Bounoura" },
		{ key: "Zelfana", value: "Zelfana" },
		{ key: "El Guerrara", value: "El Guerrara" },
		{ key: "Sebseb", value: "Sebseb" },
		{ key: "Metlili", value: "Metlili" },
		{ key: "Berriane", value: "Berriane" },
		{ key: "Ghardaia", value: "Ghardaia" },
	],
	Relizane: [
		{ key: "El-Guettar", value: "El-Guettar" },
		{ key: "Ouled Aiche", value: "Ouled Aiche" },
		{ key: "Beni Dergoun", value: "Beni Dergoun" },
		{ key: "Dar Ben Abdelah", value: "Dar Ben Abdelah" },
		{ key: "Zemmoura", value: "Zemmoura" },
		{ key: "Djidiouia", value: "Djidiouia" },
		{ key: "Hamri", value: "Hamri" },
		{ key: "Belaassel Bouzagza", value: "Belaassel Bouzagza" },
		{ key: "El-Matmar", value: "El-Matmar" },
		{ key: "Sidi Khettab", value: "Sidi Khettab" },
		{ key: "Sidi M'hamed Benaouda", value: "Sidi M'hamed Benaouda" },
		{ key: "Ain-Tarek", value: "Ain-Tarek" },
		{ key: "Had Echkalla", value: "Had Echkalla" },
		{ key: "El Ouldja", value: "El Ouldja" },
		{ key: "Mazouna", value: "Mazouna" },
		{ key: "Ain Rahma", value: "Ain Rahma" },
		{ key: "Kalaa", value: "Kalaa" },
		{ key: "Sidi Saada", value: "Sidi Saada" },
		{ key: "Yellel", value: "Yellel" },
		{ key: "Souk El Had", value: "Souk El Had" },
		{ key: "Mendes", value: "Mendes" },
		{ key: "Oued Essalem", value: "Oued Essalem" },
		{ key: "Sidi Lazreg", value: "Sidi Lazreg" },
		{ key: "Ammi Moussa", value: "Ammi Moussa" },
		{ key: "Ouarizane", value: "Ouarizane" },
		{ key: "Merdja Sidi Abed", value: "Merdja Sidi Abed" },
		{ key: "Ouled Sidi Mihoub", value: "Ouled Sidi Mihoub" },
		{ key: "Bendaoud", value: "Bendaoud" },
		{ key: "Oued-Rhiou", value: "Oued-Rhiou" },
		{ key: "El Hassi", value: "El Hassi" },
		{ key: "Sidi M'hamed Benali", value: "Sidi M'hamed Benali" },
		{ key: "Mediouna", value: "Mediouna" },
		{ key: "Beni Zentis", value: "Beni Zentis" },
		{ key: "Oued El Djemaa", value: "Oued El Djemaa" },
		{ key: "Lahlef", value: "Lahlef" },
		{ key: "Relizane", value: "Relizane" },
		{ key: "El H'madna", value: "El H'madna" },
		{ key: "Ramka", value: "Ramka" },
	],
	Timimoun: [
		{ key: "Tinerkouk", value: "Tinerkouk" },
		{ key: "Timimoun", value: "Timimoun" },
		{ key: "Ouled Said", value: "Ouled Said" },
		{ key: "Metarfa", value: "Metarfa" },
		{ key: "Talmine", value: "Talmine" },
		{ key: "Ouled Aissa", value: "Ouled Aissa" },
		{ key: "Charouine", value: "Charouine" },
		{ key: "Aougrout", value: "Aougrout" },
		{ key: "Deldoul", value: "Deldoul" },
		{ key: "Ksar Kaddour", value: "Ksar Kaddour" },
	],
	"Bordj Badji Mokhtar": [
		{ key: "Timiaouine", value: "Timiaouine" },
		{ key: "Bordj Badji Mokhtar", value: "Bordj Badji Mokhtar" },
	],
	"Ouled Djellal": [
		{ key: "Ras El Miad", value: "Ras El Miad" },
		{ key: "Besbes", value: "Besbes" },
		{ key: "Sidi Khaled", value: "Sidi Khaled" },
		{ key: "Doucen", value: "Doucen" },
		{ key: "Chaiba", value: "Chaiba" },
		{ key: "Ouled Djellal", value: "Ouled Djellal" },
	],
	"Béni Abbès": [
		{ key: "Beni-Abbes", value: "Beni-Abbes" },
		{ key: "Tamtert", value: "Tamtert" },
		{ key: "Igli", value: "Igli" },
		{ key: "El Ouata", value: "El Ouata" },
		{ key: "Ouled-Khodeir", value: "Ouled-Khodeir" },
		{ key: "Kerzaz", value: "Kerzaz" },
		{ key: "Timoudi", value: "Timoudi" },
		{ key: "Ksabi", value: "Ksabi" },
		{ key: "Beni-Ikhlef", value: "Beni-Ikhlef" },
	],
	"In Salah": [
		{ key: "Inghar", value: "Inghar" },
		{ key: "Ain Salah", value: "Ain Salah" },
		{ key: "Foggaret Ezzoua", value: "Foggaret Ezzoua" },
	],
	"In Guezzam": [
		{ key: "Tin Zouatine", value: "Tin Zouatine" },
		{ key: "Ain Guezzam", value: "Ain Guezzam" },
	],
	Touggourt: [
		{ key: "Temacine", value: "Temacine" },
		{ key: "Sidi Slimane", value: "Sidi Slimane" },
		{ key: "Megarine", value: "Megarine" },
		{ key: "Nezla", value: "Nezla" },
		{ key: "Blidet Amor", value: "Blidet Amor" },
		{ key: "Tebesbest", value: "Tebesbest" },
		{ key: "Touggourt", value: "Touggourt" },
		{ key: "Taibet", value: "Taibet" },
		{ key: "El Alia", value: "El Alia" },
		{ key: "El-Hadjira", value: "El-Hadjira" },
		{ key: "Benaceur", value: "Benaceur" },
		{ key: "M'naguer", value: "M'naguer" },
		{ key: "Zaouia El Abidia", value: "Zaouia El Abidia" },
	],
	Djanet: [
		{ key: "Djanet", value: "Djanet" },
		{ key: "Bordj El Haouass", value: "Bordj El Haouass" },
	],
	"El Meghaier": [
		{ key: "Oum Touyour", value: "Oum Touyour" },
		{ key: "Sidi Amrane", value: "Sidi Amrane" },
		{ key: "M'rara", value: "M'rara" },
		{ key: "Djamaa", value: "Djamaa" },
		{ key: "Tenedla", value: "Tenedla" },
		{ key: "El-M'ghaier", value: "El-M'ghaier" },
		{ key: "Still", value: "Still" },
		{ key: "Sidi Khelil", value: "Sidi Khelil" },
	],
	"El Menia": [
		{ key: "El Meniaa", value: "El Meniaa" },
		{ key: "Hassi Gara", value: "Hassi Gara" },
		{ key: "Hassi Fehal", value: "Hassi Fehal" },
	],
};
